/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  DeleteAttachmentsById200,
  GetAttachmentsByTaskId200,
  GetAttachmentsByTasks200,
  GetAttachmentsByTasksParams,
  GetAttachmentsDownloadById200,
  GetAttachmentsDownloadById404,
  PostAttachmentsUploadByTaskIdWithFormData201,
  PostAttachmentsUploadByTaskIdWithFormDataBodyThree,
  PostAttachmentsUploadByTaskIdWithJson201,
  PostAttachmentsUploadByTaskIdWithJsonBodyOne,
  PostAttachmentsUploadByTaskIdWithUrlEncoded201,
  PostAttachmentsUploadByTaskIdWithUrlEncodedBodyTwo,
} from './model'

export type postAttachmentsUploadByTaskIdWithJsonResponse201 = {
  data: PostAttachmentsUploadByTaskIdWithJson201
  status: 201
}

export type postAttachmentsUploadByTaskIdWithJsonResponseSuccess =
  postAttachmentsUploadByTaskIdWithJsonResponse201 & {
    headers: Headers
  }

export type postAttachmentsUploadByTaskIdWithJsonResponse =
  postAttachmentsUploadByTaskIdWithJsonResponseSuccess

export const getPostAttachmentsUploadByTaskIdWithJsonUrl = (taskId: string) => {
  return `http://localhost:3333/attachments/upload/${taskId}`
}

export const postAttachmentsUploadByTaskIdWithJson = async (
  taskId: string,
  postAttachmentsUploadByTaskIdWithJsonBodyOne: PostAttachmentsUploadByTaskIdWithJsonBodyOne,
  options?: RequestInit,
): Promise<postAttachmentsUploadByTaskIdWithJsonResponse> => {
  const res = await fetch(getPostAttachmentsUploadByTaskIdWithJsonUrl(taskId), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAttachmentsUploadByTaskIdWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postAttachmentsUploadByTaskIdWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAttachmentsUploadByTaskIdWithJsonResponse
}

export const getPostAttachmentsUploadByTaskIdWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithJson>>,
    TError,
    { taskId: string; data: PostAttachmentsUploadByTaskIdWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithJson>>,
  TError,
  { taskId: string; data: PostAttachmentsUploadByTaskIdWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['postAttachmentsUploadByTaskIdWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithJson>>,
    { taskId: string; data: PostAttachmentsUploadByTaskIdWithJsonBodyOne }
  > = (props) => {
    const { taskId, data } = props ?? {}

    return postAttachmentsUploadByTaskIdWithJson(taskId, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostAttachmentsUploadByTaskIdWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithJson>>
>
export type PostAttachmentsUploadByTaskIdWithJsonMutationBody =
  PostAttachmentsUploadByTaskIdWithJsonBodyOne
export type PostAttachmentsUploadByTaskIdWithJsonMutationError = unknown

export const usePostAttachmentsUploadByTaskIdWithJson = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithJson>>,
      TError,
      { taskId: string; data: PostAttachmentsUploadByTaskIdWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithJson>>,
  TError,
  { taskId: string; data: PostAttachmentsUploadByTaskIdWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPostAttachmentsUploadByTaskIdWithJsonMutationOptions(options),
    queryClient,
  )
}
export type postAttachmentsUploadByTaskIdWithUrlEncodedResponse201 = {
  data: PostAttachmentsUploadByTaskIdWithUrlEncoded201
  status: 201
}

export type postAttachmentsUploadByTaskIdWithUrlEncodedResponseSuccess =
  postAttachmentsUploadByTaskIdWithUrlEncodedResponse201 & {
    headers: Headers
  }

export type postAttachmentsUploadByTaskIdWithUrlEncodedResponse =
  postAttachmentsUploadByTaskIdWithUrlEncodedResponseSuccess

export const getPostAttachmentsUploadByTaskIdWithUrlEncodedUrl = (
  taskId: string,
) => {
  return `http://localhost:3333/attachments/upload/${taskId}`
}

export const postAttachmentsUploadByTaskIdWithUrlEncoded = async (
  taskId: string,
  postAttachmentsUploadByTaskIdWithUrlEncodedBodyTwo: PostAttachmentsUploadByTaskIdWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<postAttachmentsUploadByTaskIdWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(
    `file`,
    postAttachmentsUploadByTaskIdWithUrlEncodedBodyTwo.file,
  )

  const res = await fetch(
    getPostAttachmentsUploadByTaskIdWithUrlEncodedUrl(taskId),
    {
      credentials: 'include',
      ...options,
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options?.headers,
      },
      body: formUrlEncoded,
    },
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postAttachmentsUploadByTaskIdWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAttachmentsUploadByTaskIdWithUrlEncodedResponse
}

export const getPostAttachmentsUploadByTaskIdWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithUrlEncoded>>,
    TError,
    {
      taskId: string
      data: PostAttachmentsUploadByTaskIdWithUrlEncodedBodyTwo
    },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithUrlEncoded>>,
  TError,
  { taskId: string; data: PostAttachmentsUploadByTaskIdWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['postAttachmentsUploadByTaskIdWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithUrlEncoded>>,
    { taskId: string; data: PostAttachmentsUploadByTaskIdWithUrlEncodedBodyTwo }
  > = (props) => {
    const { taskId, data } = props ?? {}

    return postAttachmentsUploadByTaskIdWithUrlEncoded(
      taskId,
      data,
      fetchOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type PostAttachmentsUploadByTaskIdWithUrlEncodedMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithUrlEncoded>>
  >
export type PostAttachmentsUploadByTaskIdWithUrlEncodedMutationBody =
  PostAttachmentsUploadByTaskIdWithUrlEncodedBodyTwo
export type PostAttachmentsUploadByTaskIdWithUrlEncodedMutationError = unknown

export const usePostAttachmentsUploadByTaskIdWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithUrlEncoded>>,
      TError,
      {
        taskId: string
        data: PostAttachmentsUploadByTaskIdWithUrlEncodedBodyTwo
      },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithUrlEncoded>>,
  TError,
  { taskId: string; data: PostAttachmentsUploadByTaskIdWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPostAttachmentsUploadByTaskIdWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
export type postAttachmentsUploadByTaskIdWithFormDataResponse201 = {
  data: PostAttachmentsUploadByTaskIdWithFormData201
  status: 201
}

export type postAttachmentsUploadByTaskIdWithFormDataResponseSuccess =
  postAttachmentsUploadByTaskIdWithFormDataResponse201 & {
    headers: Headers
  }

export type postAttachmentsUploadByTaskIdWithFormDataResponse =
  postAttachmentsUploadByTaskIdWithFormDataResponseSuccess

export const getPostAttachmentsUploadByTaskIdWithFormDataUrl = (
  taskId: string,
) => {
  return `http://localhost:3333/attachments/upload/${taskId}`
}

export const postAttachmentsUploadByTaskIdWithFormData = async (
  taskId: string,
  postAttachmentsUploadByTaskIdWithFormDataBodyThree: PostAttachmentsUploadByTaskIdWithFormDataBodyThree,
  options?: RequestInit,
): Promise<postAttachmentsUploadByTaskIdWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(
    `file`,
    postAttachmentsUploadByTaskIdWithFormDataBodyThree.file,
  )

  const res = await fetch(
    getPostAttachmentsUploadByTaskIdWithFormDataUrl(taskId),
    {
      credentials: 'include',
      ...options,
      method: 'POST',
      body: formData,
    },
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postAttachmentsUploadByTaskIdWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAttachmentsUploadByTaskIdWithFormDataResponse
}

export const getPostAttachmentsUploadByTaskIdWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithFormData>>,
    TError,
    {
      taskId: string
      data: PostAttachmentsUploadByTaskIdWithFormDataBodyThree
    },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithFormData>>,
  TError,
  { taskId: string; data: PostAttachmentsUploadByTaskIdWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['postAttachmentsUploadByTaskIdWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithFormData>>,
    { taskId: string; data: PostAttachmentsUploadByTaskIdWithFormDataBodyThree }
  > = (props) => {
    const { taskId, data } = props ?? {}

    return postAttachmentsUploadByTaskIdWithFormData(taskId, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostAttachmentsUploadByTaskIdWithFormDataMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithFormData>>
  >
export type PostAttachmentsUploadByTaskIdWithFormDataMutationBody =
  PostAttachmentsUploadByTaskIdWithFormDataBodyThree
export type PostAttachmentsUploadByTaskIdWithFormDataMutationError = unknown

export const usePostAttachmentsUploadByTaskIdWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithFormData>>,
      TError,
      {
        taskId: string
        data: PostAttachmentsUploadByTaskIdWithFormDataBodyThree
      },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAttachmentsUploadByTaskIdWithFormData>>,
  TError,
  { taskId: string; data: PostAttachmentsUploadByTaskIdWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPostAttachmentsUploadByTaskIdWithFormDataMutationOptions(options),
    queryClient,
  )
}
export type getAttachmentsByTaskIdResponse200 = {
  data: GetAttachmentsByTaskId200
  status: 200
}

export type getAttachmentsByTaskIdResponseSuccess =
  getAttachmentsByTaskIdResponse200 & {
    headers: Headers
  }

export type getAttachmentsByTaskIdResponse =
  getAttachmentsByTaskIdResponseSuccess

export const getGetAttachmentsByTaskIdUrl = (taskId: string) => {
  return `http://localhost:3333/attachments/${taskId}`
}

export const getAttachmentsByTaskId = async (
  taskId: string,
  options?: RequestInit,
): Promise<getAttachmentsByTaskIdResponse> => {
  const res = await fetch(getGetAttachmentsByTaskIdUrl(taskId), {
    credentials: 'include',
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getAttachmentsByTaskIdResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAttachmentsByTaskIdResponse
}

export const getGetAttachmentsByTaskIdQueryKey = (taskId: string) => {
  return [`http://localhost:3333/attachments/${taskId}`] as const
}

export const getGetAttachmentsByTaskIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetAttachmentsByTaskIdQueryKey(taskId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAttachmentsByTaskId>>
  > = ({ signal }) =>
    getAttachmentsByTaskId(taskId, { signal, ...fetchOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!taskId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAttachmentsByTaskIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAttachmentsByTaskId>>
>
export type GetAttachmentsByTaskIdQueryError = unknown

export function useGetAttachmentsByTaskId<
  TData = Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
  TError = unknown,
>(
  taskId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
          TError,
          Awaited<ReturnType<typeof getAttachmentsByTaskId>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAttachmentsByTaskId<
  TData = Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
          TError,
          Awaited<ReturnType<typeof getAttachmentsByTaskId>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAttachmentsByTaskId<
  TData = Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetAttachmentsByTaskId<
  TData = Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsByTaskId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAttachmentsByTaskIdQueryOptions(taskId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getAttachmentsByTasksResponse200 = {
  data: GetAttachmentsByTasks200
  status: 200
}

export type getAttachmentsByTasksResponseSuccess =
  getAttachmentsByTasksResponse200 & {
    headers: Headers
  }

export type getAttachmentsByTasksResponse = getAttachmentsByTasksResponseSuccess

export const getGetAttachmentsByTasksUrl = (
  params?: GetAttachmentsByTasksParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://localhost:3333/attachments/by-tasks?${stringifiedParams}`
    : `http://localhost:3333/attachments/by-tasks`
}

export const getAttachmentsByTasks = async (
  params?: GetAttachmentsByTasksParams,
  options?: RequestInit,
): Promise<getAttachmentsByTasksResponse> => {
  const res = await fetch(getGetAttachmentsByTasksUrl(params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getAttachmentsByTasksResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAttachmentsByTasksResponse
}

export const getGetAttachmentsByTasksQueryKey = (
  params?: GetAttachmentsByTasksParams,
) => {
  return [
    `http://localhost:3333/attachments/by-tasks`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetAttachmentsByTasksQueryOptions = <
  TData = Awaited<ReturnType<typeof getAttachmentsByTasks>>,
  TError = unknown,
>(
  params?: GetAttachmentsByTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsByTasks>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetAttachmentsByTasksQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAttachmentsByTasks>>
  > = ({ signal }) => getAttachmentsByTasks(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAttachmentsByTasks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAttachmentsByTasksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAttachmentsByTasks>>
>
export type GetAttachmentsByTasksQueryError = unknown

export function useGetAttachmentsByTasks<
  TData = Awaited<ReturnType<typeof getAttachmentsByTasks>>,
  TError = unknown,
>(
  params: undefined | GetAttachmentsByTasksParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsByTasks>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttachmentsByTasks>>,
          TError,
          Awaited<ReturnType<typeof getAttachmentsByTasks>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAttachmentsByTasks<
  TData = Awaited<ReturnType<typeof getAttachmentsByTasks>>,
  TError = unknown,
>(
  params?: GetAttachmentsByTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsByTasks>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttachmentsByTasks>>,
          TError,
          Awaited<ReturnType<typeof getAttachmentsByTasks>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAttachmentsByTasks<
  TData = Awaited<ReturnType<typeof getAttachmentsByTasks>>,
  TError = unknown,
>(
  params?: GetAttachmentsByTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsByTasks>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetAttachmentsByTasks<
  TData = Awaited<ReturnType<typeof getAttachmentsByTasks>>,
  TError = unknown,
>(
  params?: GetAttachmentsByTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsByTasks>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAttachmentsByTasksQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getAttachmentsDownloadByIdResponse200 = {
  data: GetAttachmentsDownloadById200
  status: 200
}

export type getAttachmentsDownloadByIdResponse404 = {
  data: GetAttachmentsDownloadById404
  status: 404
}

export type getAttachmentsDownloadByIdResponseSuccess =
  getAttachmentsDownloadByIdResponse200 & {
    headers: Headers
  }
export type getAttachmentsDownloadByIdResponseError =
  getAttachmentsDownloadByIdResponse404 & {
    headers: Headers
  }

export type getAttachmentsDownloadByIdResponse =
  | getAttachmentsDownloadByIdResponseSuccess
  | getAttachmentsDownloadByIdResponseError

export const getGetAttachmentsDownloadByIdUrl = (id: string) => {
  return `http://localhost:3333/attachments/download/${id}`
}

export const getAttachmentsDownloadById = async (
  id: string,
  options?: RequestInit,
): Promise<getAttachmentsDownloadByIdResponse> => {
  const res = await fetch(getGetAttachmentsDownloadByIdUrl(id), {
    credentials: 'include',
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getAttachmentsDownloadByIdResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAttachmentsDownloadByIdResponse
}

export const getGetAttachmentsDownloadByIdQueryKey = (id: string) => {
  return [`http://localhost:3333/attachments/download/${id}`] as const
}

export const getGetAttachmentsDownloadByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
  TError = GetAttachmentsDownloadById404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetAttachmentsDownloadByIdQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAttachmentsDownloadById>>
  > = ({ signal }) =>
    getAttachmentsDownloadById(id, { signal, ...fetchOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAttachmentsDownloadByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAttachmentsDownloadById>>
>
export type GetAttachmentsDownloadByIdQueryError = GetAttachmentsDownloadById404

export function useGetAttachmentsDownloadById<
  TData = Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
  TError = GetAttachmentsDownloadById404,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
          TError,
          Awaited<ReturnType<typeof getAttachmentsDownloadById>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAttachmentsDownloadById<
  TData = Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
  TError = GetAttachmentsDownloadById404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
          TError,
          Awaited<ReturnType<typeof getAttachmentsDownloadById>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAttachmentsDownloadById<
  TData = Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
  TError = GetAttachmentsDownloadById404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetAttachmentsDownloadById<
  TData = Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
  TError = GetAttachmentsDownloadById404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAttachmentsDownloadById>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAttachmentsDownloadByIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type deleteAttachmentsByIdResponse200 = {
  data: DeleteAttachmentsById200
  status: 200
}

export type deleteAttachmentsByIdResponseSuccess =
  deleteAttachmentsByIdResponse200 & {
    headers: Headers
  }

export type deleteAttachmentsByIdResponse = deleteAttachmentsByIdResponseSuccess

export const getDeleteAttachmentsByIdUrl = (id: string) => {
  return `http://localhost:3333/attachments/${id}`
}

export const deleteAttachmentsById = async (
  id: string,
  options?: RequestInit,
): Promise<deleteAttachmentsByIdResponse> => {
  const res = await fetch(getDeleteAttachmentsByIdUrl(id), {
    credentials: 'include',
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: deleteAttachmentsByIdResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteAttachmentsByIdResponse
}

export const getDeleteAttachmentsByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAttachmentsById>>,
    TError,
    { id: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAttachmentsById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteAttachmentsById']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAttachmentsById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteAttachmentsById(id, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteAttachmentsByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAttachmentsById>>
>

export type DeleteAttachmentsByIdMutationError = unknown

export const useDeleteAttachmentsById = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAttachmentsById>>,
      TError,
      { id: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAttachmentsById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteAttachmentsByIdMutationOptions(options),
    queryClient,
  )
}
