/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  GetColumnsKanban200Item,
  GetColumnsKanbanParams,
  PostColumnsWithFormData201,
  PostColumnsWithFormDataBodyThree,
  PostColumnsWithJson201,
  PostColumnsWithJsonBodyOne,
  PostColumnsWithUrlEncoded201,
  PostColumnsWithUrlEncodedBodyTwo,
  PutColumnsByIdWithFormData200,
  PutColumnsByIdWithFormDataBodyThree,
  PutColumnsByIdWithJson200,
  PutColumnsByIdWithJsonBodyOne,
  PutColumnsByIdWithUrlEncoded200,
  PutColumnsByIdWithUrlEncodedBodyTwo,
  PutColumnsPositionsWithFormDataBodyThree,
  PutColumnsPositionsWithJsonBodyOne,
  PutColumnsPositionsWithUrlEncodedBodyTwo,
} from './model'

export type postColumnsWithJsonResponse201 = {
  data: PostColumnsWithJson201
  status: 201
}

export type postColumnsWithJsonResponseSuccess =
  postColumnsWithJsonResponse201 & {
    headers: Headers
  }

export type postColumnsWithJsonResponse = postColumnsWithJsonResponseSuccess

export const getPostColumnsWithJsonUrl = () => {
  return `http://localhost:3333/columns/`
}

export const postColumnsWithJson = async (
  postColumnsWithJsonBodyOne: PostColumnsWithJsonBodyOne,
  options?: RequestInit,
): Promise<postColumnsWithJsonResponse> => {
  const res = await fetch(getPostColumnsWithJsonUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postColumnsWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postColumnsWithJsonResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postColumnsWithJsonResponse
}

export const getPostColumnsWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postColumnsWithJson>>,
    TError,
    { data: PostColumnsWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postColumnsWithJson>>,
  TError,
  { data: PostColumnsWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['postColumnsWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postColumnsWithJson>>,
    { data: PostColumnsWithJsonBodyOne }
  > = (props) => {
    const { data } = props ?? {}

    return postColumnsWithJson(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostColumnsWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postColumnsWithJson>>
>
export type PostColumnsWithJsonMutationBody = PostColumnsWithJsonBodyOne
export type PostColumnsWithJsonMutationError = unknown

export const usePostColumnsWithJson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postColumnsWithJson>>,
      TError,
      { data: PostColumnsWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postColumnsWithJson>>,
  TError,
  { data: PostColumnsWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPostColumnsWithJsonMutationOptions(options),
    queryClient,
  )
}
export type postColumnsWithUrlEncodedResponse201 = {
  data: PostColumnsWithUrlEncoded201
  status: 201
}

export type postColumnsWithUrlEncodedResponseSuccess =
  postColumnsWithUrlEncodedResponse201 & {
    headers: Headers
  }

export type postColumnsWithUrlEncodedResponse =
  postColumnsWithUrlEncodedResponseSuccess

export const getPostColumnsWithUrlEncodedUrl = () => {
  return `http://localhost:3333/columns/`
}

export const postColumnsWithUrlEncoded = async (
  postColumnsWithUrlEncodedBodyTwo: PostColumnsWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<postColumnsWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(`title`, postColumnsWithUrlEncodedBodyTwo.title)
  formUrlEncoded.append(`projectId`, postColumnsWithUrlEncodedBodyTwo.projectId)

  const res = await fetch(getPostColumnsWithUrlEncodedUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postColumnsWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postColumnsWithUrlEncodedResponse
}

export const getPostColumnsWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>,
    TError,
    { data: PostColumnsWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>,
  TError,
  { data: PostColumnsWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['postColumnsWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>,
    { data: PostColumnsWithUrlEncodedBodyTwo }
  > = (props) => {
    const { data } = props ?? {}

    return postColumnsWithUrlEncoded(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostColumnsWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>
>
export type PostColumnsWithUrlEncodedMutationBody =
  PostColumnsWithUrlEncodedBodyTwo
export type PostColumnsWithUrlEncodedMutationError = unknown

export const usePostColumnsWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>,
      TError,
      { data: PostColumnsWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>,
  TError,
  { data: PostColumnsWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPostColumnsWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
export type postColumnsWithFormDataResponse201 = {
  data: PostColumnsWithFormData201
  status: 201
}

export type postColumnsWithFormDataResponseSuccess =
  postColumnsWithFormDataResponse201 & {
    headers: Headers
  }

export type postColumnsWithFormDataResponse =
  postColumnsWithFormDataResponseSuccess

export const getPostColumnsWithFormDataUrl = () => {
  return `http://localhost:3333/columns/`
}

export const postColumnsWithFormData = async (
  postColumnsWithFormDataBodyThree: PostColumnsWithFormDataBodyThree,
  options?: RequestInit,
): Promise<postColumnsWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(`title`, postColumnsWithFormDataBodyThree.title)
  formData.append(`projectId`, postColumnsWithFormDataBodyThree.projectId)

  const res = await fetch(getPostColumnsWithFormDataUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postColumnsWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postColumnsWithFormDataResponse
}

export const getPostColumnsWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postColumnsWithFormData>>,
    TError,
    { data: PostColumnsWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postColumnsWithFormData>>,
  TError,
  { data: PostColumnsWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['postColumnsWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postColumnsWithFormData>>,
    { data: PostColumnsWithFormDataBodyThree }
  > = (props) => {
    const { data } = props ?? {}

    return postColumnsWithFormData(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostColumnsWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof postColumnsWithFormData>>
>
export type PostColumnsWithFormDataMutationBody =
  PostColumnsWithFormDataBodyThree
export type PostColumnsWithFormDataMutationError = unknown

export const usePostColumnsWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postColumnsWithFormData>>,
      TError,
      { data: PostColumnsWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postColumnsWithFormData>>,
  TError,
  { data: PostColumnsWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPostColumnsWithFormDataMutationOptions(options),
    queryClient,
  )
}
export type getColumnsKanbanResponse200 = {
  data: GetColumnsKanban200Item[]
  status: 200
}

export type getColumnsKanbanResponseSuccess = getColumnsKanbanResponse200 & {
  headers: Headers
}

export type getColumnsKanbanResponse = getColumnsKanbanResponseSuccess

export const getGetColumnsKanbanUrl = (params: GetColumnsKanbanParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://localhost:3333/columns/?${stringifiedParams}`
    : `http://localhost:3333/columns/`
}

export const getColumnsKanban = async (
  params: GetColumnsKanbanParams,
  options?: RequestInit,
): Promise<getColumnsKanbanResponse> => {
  const res = await fetch(getGetColumnsKanbanUrl(params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getColumnsKanbanResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getColumnsKanbanResponse
}

export const getGetColumnsKanbanQueryKey = (
  params?: GetColumnsKanbanParams,
) => {
  return [
    `http://localhost:3333/columns/`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetColumnsKanbanQueryOptions = <
  TData = Awaited<ReturnType<typeof getColumnsKanban>>,
  TError = unknown,
>(
  params: GetColumnsKanbanParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getColumnsKanban>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetColumnsKanbanQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getColumnsKanban>>
  > = ({ signal }) => getColumnsKanban(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getColumnsKanban>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetColumnsKanbanQueryResult = NonNullable<
  Awaited<ReturnType<typeof getColumnsKanban>>
>
export type GetColumnsKanbanQueryError = unknown

export function useGetColumnsKanban<
  TData = Awaited<ReturnType<typeof getColumnsKanban>>,
  TError = unknown,
>(
  params: GetColumnsKanbanParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getColumnsKanban>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getColumnsKanban>>,
          TError,
          Awaited<ReturnType<typeof getColumnsKanban>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetColumnsKanban<
  TData = Awaited<ReturnType<typeof getColumnsKanban>>,
  TError = unknown,
>(
  params: GetColumnsKanbanParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getColumnsKanban>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getColumnsKanban>>,
          TError,
          Awaited<ReturnType<typeof getColumnsKanban>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetColumnsKanban<
  TData = Awaited<ReturnType<typeof getColumnsKanban>>,
  TError = unknown,
>(
  params: GetColumnsKanbanParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getColumnsKanban>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetColumnsKanban<
  TData = Awaited<ReturnType<typeof getColumnsKanban>>,
  TError = unknown,
>(
  params: GetColumnsKanbanParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getColumnsKanban>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetColumnsKanbanQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type putColumnsPositionsWithJsonResponse200 = {
  data: void
  status: 200
}

export type putColumnsPositionsWithJsonResponseSuccess =
  putColumnsPositionsWithJsonResponse200 & {
    headers: Headers
  }

export type putColumnsPositionsWithJsonResponse =
  putColumnsPositionsWithJsonResponseSuccess

export const getPutColumnsPositionsWithJsonUrl = () => {
  return `http://localhost:3333/columns/positions`
}

export const putColumnsPositionsWithJson = async (
  putColumnsPositionsWithJsonBodyOne: PutColumnsPositionsWithJsonBodyOne,
  options?: RequestInit,
): Promise<putColumnsPositionsWithJsonResponse> => {
  const res = await fetch(getPutColumnsPositionsWithJsonUrl(), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putColumnsPositionsWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putColumnsPositionsWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putColumnsPositionsWithJsonResponse
}

export const getPutColumnsPositionsWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putColumnsPositionsWithJson>>,
    TError,
    { data: PutColumnsPositionsWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putColumnsPositionsWithJson>>,
  TError,
  { data: PutColumnsPositionsWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['putColumnsPositionsWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putColumnsPositionsWithJson>>,
    { data: PutColumnsPositionsWithJsonBodyOne }
  > = (props) => {
    const { data } = props ?? {}

    return putColumnsPositionsWithJson(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutColumnsPositionsWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof putColumnsPositionsWithJson>>
>
export type PutColumnsPositionsWithJsonMutationBody =
  PutColumnsPositionsWithJsonBodyOne
export type PutColumnsPositionsWithJsonMutationError = unknown

export const usePutColumnsPositionsWithJson = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putColumnsPositionsWithJson>>,
      TError,
      { data: PutColumnsPositionsWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putColumnsPositionsWithJson>>,
  TError,
  { data: PutColumnsPositionsWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPutColumnsPositionsWithJsonMutationOptions(options),
    queryClient,
  )
}
export type putColumnsPositionsWithUrlEncodedResponse200 = {
  data: void
  status: 200
}

export type putColumnsPositionsWithUrlEncodedResponseSuccess =
  putColumnsPositionsWithUrlEncodedResponse200 & {
    headers: Headers
  }

export type putColumnsPositionsWithUrlEncodedResponse =
  putColumnsPositionsWithUrlEncodedResponseSuccess

export const getPutColumnsPositionsWithUrlEncodedUrl = () => {
  return `http://localhost:3333/columns/positions`
}

export const putColumnsPositionsWithUrlEncoded = async (
  putColumnsPositionsWithUrlEncodedBodyTwo: PutColumnsPositionsWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<putColumnsPositionsWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(
    `projectId`,
    putColumnsPositionsWithUrlEncodedBodyTwo.projectId,
  )
  putColumnsPositionsWithUrlEncodedBodyTwo.columnIds.forEach((value) =>
    formUrlEncoded.append(`columnIds`, value),
  )

  const res = await fetch(getPutColumnsPositionsWithUrlEncodedUrl(), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putColumnsPositionsWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putColumnsPositionsWithUrlEncodedResponse
}

export const getPutColumnsPositionsWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putColumnsPositionsWithUrlEncoded>>,
    TError,
    { data: PutColumnsPositionsWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putColumnsPositionsWithUrlEncoded>>,
  TError,
  { data: PutColumnsPositionsWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['putColumnsPositionsWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putColumnsPositionsWithUrlEncoded>>,
    { data: PutColumnsPositionsWithUrlEncodedBodyTwo }
  > = (props) => {
    const { data } = props ?? {}

    return putColumnsPositionsWithUrlEncoded(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutColumnsPositionsWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof putColumnsPositionsWithUrlEncoded>>
>
export type PutColumnsPositionsWithUrlEncodedMutationBody =
  PutColumnsPositionsWithUrlEncodedBodyTwo
export type PutColumnsPositionsWithUrlEncodedMutationError = unknown

export const usePutColumnsPositionsWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putColumnsPositionsWithUrlEncoded>>,
      TError,
      { data: PutColumnsPositionsWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putColumnsPositionsWithUrlEncoded>>,
  TError,
  { data: PutColumnsPositionsWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPutColumnsPositionsWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
export type putColumnsPositionsWithFormDataResponse200 = {
  data: void
  status: 200
}

export type putColumnsPositionsWithFormDataResponseSuccess =
  putColumnsPositionsWithFormDataResponse200 & {
    headers: Headers
  }

export type putColumnsPositionsWithFormDataResponse =
  putColumnsPositionsWithFormDataResponseSuccess

export const getPutColumnsPositionsWithFormDataUrl = () => {
  return `http://localhost:3333/columns/positions`
}

export const putColumnsPositionsWithFormData = async (
  putColumnsPositionsWithFormDataBodyThree: PutColumnsPositionsWithFormDataBodyThree,
  options?: RequestInit,
): Promise<putColumnsPositionsWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(
    `projectId`,
    putColumnsPositionsWithFormDataBodyThree.projectId,
  )
  putColumnsPositionsWithFormDataBodyThree.columnIds.forEach((value) =>
    formData.append(`columnIds`, value),
  )

  const res = await fetch(getPutColumnsPositionsWithFormDataUrl(), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putColumnsPositionsWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putColumnsPositionsWithFormDataResponse
}

export const getPutColumnsPositionsWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putColumnsPositionsWithFormData>>,
    TError,
    { data: PutColumnsPositionsWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putColumnsPositionsWithFormData>>,
  TError,
  { data: PutColumnsPositionsWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['putColumnsPositionsWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putColumnsPositionsWithFormData>>,
    { data: PutColumnsPositionsWithFormDataBodyThree }
  > = (props) => {
    const { data } = props ?? {}

    return putColumnsPositionsWithFormData(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutColumnsPositionsWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof putColumnsPositionsWithFormData>>
>
export type PutColumnsPositionsWithFormDataMutationBody =
  PutColumnsPositionsWithFormDataBodyThree
export type PutColumnsPositionsWithFormDataMutationError = unknown

export const usePutColumnsPositionsWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putColumnsPositionsWithFormData>>,
      TError,
      { data: PutColumnsPositionsWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putColumnsPositionsWithFormData>>,
  TError,
  { data: PutColumnsPositionsWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPutColumnsPositionsWithFormDataMutationOptions(options),
    queryClient,
  )
}
export type putColumnsByIdWithJsonResponse200 = {
  data: PutColumnsByIdWithJson200
  status: 200
}

export type putColumnsByIdWithJsonResponseSuccess =
  putColumnsByIdWithJsonResponse200 & {
    headers: Headers
  }

export type putColumnsByIdWithJsonResponse =
  putColumnsByIdWithJsonResponseSuccess

export const getPutColumnsByIdWithJsonUrl = (id: string) => {
  return `http://localhost:3333/columns/${id}`
}

export const putColumnsByIdWithJson = async (
  id: string,
  putColumnsByIdWithJsonBodyOne: PutColumnsByIdWithJsonBodyOne,
  options?: RequestInit,
): Promise<putColumnsByIdWithJsonResponse> => {
  const res = await fetch(getPutColumnsByIdWithJsonUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putColumnsByIdWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putColumnsByIdWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putColumnsByIdWithJsonResponse
}

export const getPutColumnsByIdWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putColumnsByIdWithJson>>,
    TError,
    { id: string; data: PutColumnsByIdWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putColumnsByIdWithJson>>,
  TError,
  { id: string; data: PutColumnsByIdWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['putColumnsByIdWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putColumnsByIdWithJson>>,
    { id: string; data: PutColumnsByIdWithJsonBodyOne }
  > = (props) => {
    const { id, data } = props ?? {}

    return putColumnsByIdWithJson(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutColumnsByIdWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof putColumnsByIdWithJson>>
>
export type PutColumnsByIdWithJsonMutationBody = PutColumnsByIdWithJsonBodyOne
export type PutColumnsByIdWithJsonMutationError = unknown

export const usePutColumnsByIdWithJson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putColumnsByIdWithJson>>,
      TError,
      { id: string; data: PutColumnsByIdWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putColumnsByIdWithJson>>,
  TError,
  { id: string; data: PutColumnsByIdWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPutColumnsByIdWithJsonMutationOptions(options),
    queryClient,
  )
}
export type putColumnsByIdWithUrlEncodedResponse200 = {
  data: PutColumnsByIdWithUrlEncoded200
  status: 200
}

export type putColumnsByIdWithUrlEncodedResponseSuccess =
  putColumnsByIdWithUrlEncodedResponse200 & {
    headers: Headers
  }

export type putColumnsByIdWithUrlEncodedResponse =
  putColumnsByIdWithUrlEncodedResponseSuccess

export const getPutColumnsByIdWithUrlEncodedUrl = (id: string) => {
  return `http://localhost:3333/columns/${id}`
}

export const putColumnsByIdWithUrlEncoded = async (
  id: string,
  putColumnsByIdWithUrlEncodedBodyTwo: PutColumnsByIdWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<putColumnsByIdWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  if (putColumnsByIdWithUrlEncodedBodyTwo.title !== undefined) {
    formUrlEncoded.append(`title`, putColumnsByIdWithUrlEncodedBodyTwo.title)
  }

  const res = await fetch(getPutColumnsByIdWithUrlEncodedUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putColumnsByIdWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putColumnsByIdWithUrlEncodedResponse
}

export const getPutColumnsByIdWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>,
    TError,
    { id: string; data: PutColumnsByIdWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>,
  TError,
  { id: string; data: PutColumnsByIdWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['putColumnsByIdWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>,
    { id: string; data: PutColumnsByIdWithUrlEncodedBodyTwo }
  > = (props) => {
    const { id, data } = props ?? {}

    return putColumnsByIdWithUrlEncoded(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutColumnsByIdWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>
>
export type PutColumnsByIdWithUrlEncodedMutationBody =
  PutColumnsByIdWithUrlEncodedBodyTwo
export type PutColumnsByIdWithUrlEncodedMutationError = unknown

export const usePutColumnsByIdWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>,
      TError,
      { id: string; data: PutColumnsByIdWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>,
  TError,
  { id: string; data: PutColumnsByIdWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPutColumnsByIdWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
export type putColumnsByIdWithFormDataResponse200 = {
  data: PutColumnsByIdWithFormData200
  status: 200
}

export type putColumnsByIdWithFormDataResponseSuccess =
  putColumnsByIdWithFormDataResponse200 & {
    headers: Headers
  }

export type putColumnsByIdWithFormDataResponse =
  putColumnsByIdWithFormDataResponseSuccess

export const getPutColumnsByIdWithFormDataUrl = (id: string) => {
  return `http://localhost:3333/columns/${id}`
}

export const putColumnsByIdWithFormData = async (
  id: string,
  putColumnsByIdWithFormDataBodyThree: PutColumnsByIdWithFormDataBodyThree,
  options?: RequestInit,
): Promise<putColumnsByIdWithFormDataResponse> => {
  const formData = new FormData()
  if (putColumnsByIdWithFormDataBodyThree.title !== undefined) {
    formData.append(`title`, putColumnsByIdWithFormDataBodyThree.title)
  }

  const res = await fetch(getPutColumnsByIdWithFormDataUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putColumnsByIdWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putColumnsByIdWithFormDataResponse
}

export const getPutColumnsByIdWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putColumnsByIdWithFormData>>,
    TError,
    { id: string; data: PutColumnsByIdWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putColumnsByIdWithFormData>>,
  TError,
  { id: string; data: PutColumnsByIdWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['putColumnsByIdWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putColumnsByIdWithFormData>>,
    { id: string; data: PutColumnsByIdWithFormDataBodyThree }
  > = (props) => {
    const { id, data } = props ?? {}

    return putColumnsByIdWithFormData(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutColumnsByIdWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof putColumnsByIdWithFormData>>
>
export type PutColumnsByIdWithFormDataMutationBody =
  PutColumnsByIdWithFormDataBodyThree
export type PutColumnsByIdWithFormDataMutationError = unknown

export const usePutColumnsByIdWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putColumnsByIdWithFormData>>,
      TError,
      { id: string; data: PutColumnsByIdWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putColumnsByIdWithFormData>>,
  TError,
  { id: string; data: PutColumnsByIdWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPutColumnsByIdWithFormDataMutationOptions(options),
    queryClient,
  )
}
export type deleteColumnsByIdResponse200 = {
  data: void
  status: 200
}

export type deleteColumnsByIdResponseSuccess = deleteColumnsByIdResponse200 & {
  headers: Headers
}

export type deleteColumnsByIdResponse = deleteColumnsByIdResponseSuccess

export const getDeleteColumnsByIdUrl = (id: string) => {
  return `http://localhost:3333/columns/${id}`
}

export const deleteColumnsById = async (
  id: string,
  options?: RequestInit,
): Promise<deleteColumnsByIdResponse> => {
  const res = await fetch(getDeleteColumnsByIdUrl(id), {
    credentials: 'include',
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: deleteColumnsByIdResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteColumnsByIdResponse
}

export const getDeleteColumnsByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteColumnsById>>,
    TError,
    { id: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteColumnsById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteColumnsById']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteColumnsById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteColumnsById(id, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteColumnsByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteColumnsById>>
>

export type DeleteColumnsByIdMutationError = unknown

export const useDeleteColumnsById = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteColumnsById>>,
      TError,
      { id: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteColumnsById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteColumnsByIdMutationOptions(options), queryClient)
}
