/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  GetColumns200,
  GetColumnsParams,
  PostColumnsReorderWithFormDataBodyThree,
  PostColumnsReorderWithJsonBodyOne,
  PostColumnsReorderWithUrlEncodedBodyTwo,
  PostColumnsWithFormData201,
  PostColumnsWithFormDataBodyThree,
  PostColumnsWithJson201,
  PostColumnsWithJsonBodyOne,
  PostColumnsWithUrlEncoded201,
  PostColumnsWithUrlEncodedBodyTwo,
  PutColumnsByIdWithFormData200,
  PutColumnsByIdWithFormDataBodyThree,
  PutColumnsByIdWithJson200,
  PutColumnsByIdWithJsonBodyOne,
  PutColumnsByIdWithUrlEncoded200,
  PutColumnsByIdWithUrlEncodedBodyTwo,
} from './model'

export type postColumnsWithJsonResponse201 = {
  data: PostColumnsWithJson201
  status: 201
}

export type postColumnsWithJsonResponseSuccess =
  postColumnsWithJsonResponse201 & {
    headers: Headers
  }

export type postColumnsWithJsonResponse = postColumnsWithJsonResponseSuccess

export const getPostColumnsWithJsonUrl = () => {
  return `http://localhost:3333/columns/`
}

export const postColumnsWithJson = async (
  postColumnsWithJsonBodyOne: PostColumnsWithJsonBodyOne,
  options?: RequestInit,
): Promise<postColumnsWithJsonResponse> => {
  const res = await fetch(getPostColumnsWithJsonUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postColumnsWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postColumnsWithJsonResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postColumnsWithJsonResponse
}

export const getPostColumnsWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postColumnsWithJson>>,
    TError,
    { data: PostColumnsWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postColumnsWithJson>>,
  TError,
  { data: PostColumnsWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['postColumnsWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postColumnsWithJson>>,
    { data: PostColumnsWithJsonBodyOne }
  > = (props) => {
    const { data } = props ?? {}

    return postColumnsWithJson(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostColumnsWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postColumnsWithJson>>
>
export type PostColumnsWithJsonMutationBody = PostColumnsWithJsonBodyOne
export type PostColumnsWithJsonMutationError = unknown

export const usePostColumnsWithJson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postColumnsWithJson>>,
      TError,
      { data: PostColumnsWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postColumnsWithJson>>,
  TError,
  { data: PostColumnsWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPostColumnsWithJsonMutationOptions(options),
    queryClient,
  )
}
export type postColumnsWithUrlEncodedResponse201 = {
  data: PostColumnsWithUrlEncoded201
  status: 201
}

export type postColumnsWithUrlEncodedResponseSuccess =
  postColumnsWithUrlEncodedResponse201 & {
    headers: Headers
  }

export type postColumnsWithUrlEncodedResponse =
  postColumnsWithUrlEncodedResponseSuccess

export const getPostColumnsWithUrlEncodedUrl = () => {
  return `http://localhost:3333/columns/`
}

export const postColumnsWithUrlEncoded = async (
  postColumnsWithUrlEncodedBodyTwo: PostColumnsWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<postColumnsWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(`title`, postColumnsWithUrlEncodedBodyTwo.title)
  formUrlEncoded.append(`projectId`, postColumnsWithUrlEncodedBodyTwo.projectId)

  const res = await fetch(getPostColumnsWithUrlEncodedUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postColumnsWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postColumnsWithUrlEncodedResponse
}

export const getPostColumnsWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>,
    TError,
    { data: PostColumnsWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>,
  TError,
  { data: PostColumnsWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['postColumnsWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>,
    { data: PostColumnsWithUrlEncodedBodyTwo }
  > = (props) => {
    const { data } = props ?? {}

    return postColumnsWithUrlEncoded(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostColumnsWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>
>
export type PostColumnsWithUrlEncodedMutationBody =
  PostColumnsWithUrlEncodedBodyTwo
export type PostColumnsWithUrlEncodedMutationError = unknown

export const usePostColumnsWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>,
      TError,
      { data: PostColumnsWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postColumnsWithUrlEncoded>>,
  TError,
  { data: PostColumnsWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPostColumnsWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
export type postColumnsWithFormDataResponse201 = {
  data: PostColumnsWithFormData201
  status: 201
}

export type postColumnsWithFormDataResponseSuccess =
  postColumnsWithFormDataResponse201 & {
    headers: Headers
  }

export type postColumnsWithFormDataResponse =
  postColumnsWithFormDataResponseSuccess

export const getPostColumnsWithFormDataUrl = () => {
  return `http://localhost:3333/columns/`
}

export const postColumnsWithFormData = async (
  postColumnsWithFormDataBodyThree: PostColumnsWithFormDataBodyThree,
  options?: RequestInit,
): Promise<postColumnsWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(`title`, postColumnsWithFormDataBodyThree.title)
  formData.append(`projectId`, postColumnsWithFormDataBodyThree.projectId)

  const res = await fetch(getPostColumnsWithFormDataUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postColumnsWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postColumnsWithFormDataResponse
}

export const getPostColumnsWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postColumnsWithFormData>>,
    TError,
    { data: PostColumnsWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postColumnsWithFormData>>,
  TError,
  { data: PostColumnsWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['postColumnsWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postColumnsWithFormData>>,
    { data: PostColumnsWithFormDataBodyThree }
  > = (props) => {
    const { data } = props ?? {}

    return postColumnsWithFormData(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostColumnsWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof postColumnsWithFormData>>
>
export type PostColumnsWithFormDataMutationBody =
  PostColumnsWithFormDataBodyThree
export type PostColumnsWithFormDataMutationError = unknown

export const usePostColumnsWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postColumnsWithFormData>>,
      TError,
      { data: PostColumnsWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postColumnsWithFormData>>,
  TError,
  { data: PostColumnsWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPostColumnsWithFormDataMutationOptions(options),
    queryClient,
  )
}
export type getColumnsResponse200 = {
  data: GetColumns200
  status: 200
}

export type getColumnsResponseSuccess = getColumnsResponse200 & {
  headers: Headers
}

export type getColumnsResponse = getColumnsResponseSuccess

export const getGetColumnsUrl = (params: GetColumnsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://localhost:3333/columns/?${stringifiedParams}`
    : `http://localhost:3333/columns/`
}

export const getColumns = async (
  params: GetColumnsParams,
  options?: RequestInit,
): Promise<getColumnsResponse> => {
  const res = await fetch(getGetColumnsUrl(params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getColumnsResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getColumnsResponse
}

export const getGetColumnsQueryKey = (params?: GetColumnsParams) => {
  return [
    `http://localhost:3333/columns/`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetColumnsQueryOptions = <
  TData = Awaited<ReturnType<typeof getColumns>>,
  TError = unknown,
>(
  params: GetColumnsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getColumns>>, TError, TData>
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetColumnsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getColumns>>> = ({
    signal,
  }) => getColumns(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getColumns>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetColumnsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getColumns>>
>
export type GetColumnsQueryError = unknown

export function useGetColumns<
  TData = Awaited<ReturnType<typeof getColumns>>,
  TError = unknown,
>(
  params: GetColumnsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getColumns>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getColumns>>,
          TError,
          Awaited<ReturnType<typeof getColumns>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetColumns<
  TData = Awaited<ReturnType<typeof getColumns>>,
  TError = unknown,
>(
  params: GetColumnsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getColumns>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getColumns>>,
          TError,
          Awaited<ReturnType<typeof getColumns>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetColumns<
  TData = Awaited<ReturnType<typeof getColumns>>,
  TError = unknown,
>(
  params: GetColumnsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getColumns>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetColumns<
  TData = Awaited<ReturnType<typeof getColumns>>,
  TError = unknown,
>(
  params: GetColumnsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getColumns>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetColumnsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type postColumnsReorderWithJsonResponse200 = {
  data: void
  status: 200
}

export type postColumnsReorderWithJsonResponseSuccess =
  postColumnsReorderWithJsonResponse200 & {
    headers: Headers
  }

export type postColumnsReorderWithJsonResponse =
  postColumnsReorderWithJsonResponseSuccess

export const getPostColumnsReorderWithJsonUrl = () => {
  return `http://localhost:3333/columns/reorder`
}

export const postColumnsReorderWithJson = async (
  postColumnsReorderWithJsonBodyOne: PostColumnsReorderWithJsonBodyOne,
  options?: RequestInit,
): Promise<postColumnsReorderWithJsonResponse> => {
  const res = await fetch(getPostColumnsReorderWithJsonUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postColumnsReorderWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postColumnsReorderWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postColumnsReorderWithJsonResponse
}

export const getPostColumnsReorderWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postColumnsReorderWithJson>>,
    TError,
    { data: PostColumnsReorderWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postColumnsReorderWithJson>>,
  TError,
  { data: PostColumnsReorderWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['postColumnsReorderWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postColumnsReorderWithJson>>,
    { data: PostColumnsReorderWithJsonBodyOne }
  > = (props) => {
    const { data } = props ?? {}

    return postColumnsReorderWithJson(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostColumnsReorderWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postColumnsReorderWithJson>>
>
export type PostColumnsReorderWithJsonMutationBody =
  PostColumnsReorderWithJsonBodyOne
export type PostColumnsReorderWithJsonMutationError = unknown

export const usePostColumnsReorderWithJson = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postColumnsReorderWithJson>>,
      TError,
      { data: PostColumnsReorderWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postColumnsReorderWithJson>>,
  TError,
  { data: PostColumnsReorderWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPostColumnsReorderWithJsonMutationOptions(options),
    queryClient,
  )
}
export type postColumnsReorderWithUrlEncodedResponse200 = {
  data: void
  status: 200
}

export type postColumnsReorderWithUrlEncodedResponseSuccess =
  postColumnsReorderWithUrlEncodedResponse200 & {
    headers: Headers
  }

export type postColumnsReorderWithUrlEncodedResponse =
  postColumnsReorderWithUrlEncodedResponseSuccess

export const getPostColumnsReorderWithUrlEncodedUrl = () => {
  return `http://localhost:3333/columns/reorder`
}

export const postColumnsReorderWithUrlEncoded = async (
  postColumnsReorderWithUrlEncodedBodyTwo: PostColumnsReorderWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<postColumnsReorderWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(
    `activeId`,
    postColumnsReorderWithUrlEncodedBodyTwo.activeId,
  )
  formUrlEncoded.append(
    `overId`,
    postColumnsReorderWithUrlEncodedBodyTwo.overId,
  )

  const res = await fetch(getPostColumnsReorderWithUrlEncodedUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postColumnsReorderWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postColumnsReorderWithUrlEncodedResponse
}

export const getPostColumnsReorderWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postColumnsReorderWithUrlEncoded>>,
    TError,
    { data: PostColumnsReorderWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postColumnsReorderWithUrlEncoded>>,
  TError,
  { data: PostColumnsReorderWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['postColumnsReorderWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postColumnsReorderWithUrlEncoded>>,
    { data: PostColumnsReorderWithUrlEncodedBodyTwo }
  > = (props) => {
    const { data } = props ?? {}

    return postColumnsReorderWithUrlEncoded(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostColumnsReorderWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof postColumnsReorderWithUrlEncoded>>
>
export type PostColumnsReorderWithUrlEncodedMutationBody =
  PostColumnsReorderWithUrlEncodedBodyTwo
export type PostColumnsReorderWithUrlEncodedMutationError = unknown

export const usePostColumnsReorderWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postColumnsReorderWithUrlEncoded>>,
      TError,
      { data: PostColumnsReorderWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postColumnsReorderWithUrlEncoded>>,
  TError,
  { data: PostColumnsReorderWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPostColumnsReorderWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
export type postColumnsReorderWithFormDataResponse200 = {
  data: void
  status: 200
}

export type postColumnsReorderWithFormDataResponseSuccess =
  postColumnsReorderWithFormDataResponse200 & {
    headers: Headers
  }

export type postColumnsReorderWithFormDataResponse =
  postColumnsReorderWithFormDataResponseSuccess

export const getPostColumnsReorderWithFormDataUrl = () => {
  return `http://localhost:3333/columns/reorder`
}

export const postColumnsReorderWithFormData = async (
  postColumnsReorderWithFormDataBodyThree: PostColumnsReorderWithFormDataBodyThree,
  options?: RequestInit,
): Promise<postColumnsReorderWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(`activeId`, postColumnsReorderWithFormDataBodyThree.activeId)
  formData.append(`overId`, postColumnsReorderWithFormDataBodyThree.overId)

  const res = await fetch(getPostColumnsReorderWithFormDataUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postColumnsReorderWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postColumnsReorderWithFormDataResponse
}

export const getPostColumnsReorderWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postColumnsReorderWithFormData>>,
    TError,
    { data: PostColumnsReorderWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postColumnsReorderWithFormData>>,
  TError,
  { data: PostColumnsReorderWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['postColumnsReorderWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postColumnsReorderWithFormData>>,
    { data: PostColumnsReorderWithFormDataBodyThree }
  > = (props) => {
    const { data } = props ?? {}

    return postColumnsReorderWithFormData(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostColumnsReorderWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof postColumnsReorderWithFormData>>
>
export type PostColumnsReorderWithFormDataMutationBody =
  PostColumnsReorderWithFormDataBodyThree
export type PostColumnsReorderWithFormDataMutationError = unknown

export const usePostColumnsReorderWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postColumnsReorderWithFormData>>,
      TError,
      { data: PostColumnsReorderWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postColumnsReorderWithFormData>>,
  TError,
  { data: PostColumnsReorderWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPostColumnsReorderWithFormDataMutationOptions(options),
    queryClient,
  )
}
export type putColumnsByIdWithJsonResponse200 = {
  data: PutColumnsByIdWithJson200
  status: 200
}

export type putColumnsByIdWithJsonResponseSuccess =
  putColumnsByIdWithJsonResponse200 & {
    headers: Headers
  }

export type putColumnsByIdWithJsonResponse =
  putColumnsByIdWithJsonResponseSuccess

export const getPutColumnsByIdWithJsonUrl = (id: string) => {
  return `http://localhost:3333/columns/${id}`
}

export const putColumnsByIdWithJson = async (
  id: string,
  putColumnsByIdWithJsonBodyOne: PutColumnsByIdWithJsonBodyOne,
  options?: RequestInit,
): Promise<putColumnsByIdWithJsonResponse> => {
  const res = await fetch(getPutColumnsByIdWithJsonUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putColumnsByIdWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putColumnsByIdWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putColumnsByIdWithJsonResponse
}

export const getPutColumnsByIdWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putColumnsByIdWithJson>>,
    TError,
    { id: string; data: PutColumnsByIdWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putColumnsByIdWithJson>>,
  TError,
  { id: string; data: PutColumnsByIdWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['putColumnsByIdWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putColumnsByIdWithJson>>,
    { id: string; data: PutColumnsByIdWithJsonBodyOne }
  > = (props) => {
    const { id, data } = props ?? {}

    return putColumnsByIdWithJson(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutColumnsByIdWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof putColumnsByIdWithJson>>
>
export type PutColumnsByIdWithJsonMutationBody = PutColumnsByIdWithJsonBodyOne
export type PutColumnsByIdWithJsonMutationError = unknown

export const usePutColumnsByIdWithJson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putColumnsByIdWithJson>>,
      TError,
      { id: string; data: PutColumnsByIdWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putColumnsByIdWithJson>>,
  TError,
  { id: string; data: PutColumnsByIdWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPutColumnsByIdWithJsonMutationOptions(options),
    queryClient,
  )
}
export type putColumnsByIdWithUrlEncodedResponse200 = {
  data: PutColumnsByIdWithUrlEncoded200
  status: 200
}

export type putColumnsByIdWithUrlEncodedResponseSuccess =
  putColumnsByIdWithUrlEncodedResponse200 & {
    headers: Headers
  }

export type putColumnsByIdWithUrlEncodedResponse =
  putColumnsByIdWithUrlEncodedResponseSuccess

export const getPutColumnsByIdWithUrlEncodedUrl = (id: string) => {
  return `http://localhost:3333/columns/${id}`
}

export const putColumnsByIdWithUrlEncoded = async (
  id: string,
  putColumnsByIdWithUrlEncodedBodyTwo: PutColumnsByIdWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<putColumnsByIdWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  if (putColumnsByIdWithUrlEncodedBodyTwo.title !== undefined) {
    formUrlEncoded.append(`title`, putColumnsByIdWithUrlEncodedBodyTwo.title)
  }
  if (putColumnsByIdWithUrlEncodedBodyTwo.order !== undefined) {
    formUrlEncoded.append(
      `order`,
      putColumnsByIdWithUrlEncodedBodyTwo.order.toString(),
    )
  }

  const res = await fetch(getPutColumnsByIdWithUrlEncodedUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putColumnsByIdWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putColumnsByIdWithUrlEncodedResponse
}

export const getPutColumnsByIdWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>,
    TError,
    { id: string; data: PutColumnsByIdWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>,
  TError,
  { id: string; data: PutColumnsByIdWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['putColumnsByIdWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>,
    { id: string; data: PutColumnsByIdWithUrlEncodedBodyTwo }
  > = (props) => {
    const { id, data } = props ?? {}

    return putColumnsByIdWithUrlEncoded(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutColumnsByIdWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>
>
export type PutColumnsByIdWithUrlEncodedMutationBody =
  PutColumnsByIdWithUrlEncodedBodyTwo
export type PutColumnsByIdWithUrlEncodedMutationError = unknown

export const usePutColumnsByIdWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>,
      TError,
      { id: string; data: PutColumnsByIdWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putColumnsByIdWithUrlEncoded>>,
  TError,
  { id: string; data: PutColumnsByIdWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPutColumnsByIdWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
export type putColumnsByIdWithFormDataResponse200 = {
  data: PutColumnsByIdWithFormData200
  status: 200
}

export type putColumnsByIdWithFormDataResponseSuccess =
  putColumnsByIdWithFormDataResponse200 & {
    headers: Headers
  }

export type putColumnsByIdWithFormDataResponse =
  putColumnsByIdWithFormDataResponseSuccess

export const getPutColumnsByIdWithFormDataUrl = (id: string) => {
  return `http://localhost:3333/columns/${id}`
}

export const putColumnsByIdWithFormData = async (
  id: string,
  putColumnsByIdWithFormDataBodyThree: PutColumnsByIdWithFormDataBodyThree,
  options?: RequestInit,
): Promise<putColumnsByIdWithFormDataResponse> => {
  const formData = new FormData()
  if (putColumnsByIdWithFormDataBodyThree.title !== undefined) {
    formData.append(`title`, putColumnsByIdWithFormDataBodyThree.title)
  }
  if (putColumnsByIdWithFormDataBodyThree.order !== undefined) {
    formData.append(
      `order`,
      putColumnsByIdWithFormDataBodyThree.order.toString(),
    )
  }

  const res = await fetch(getPutColumnsByIdWithFormDataUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putColumnsByIdWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putColumnsByIdWithFormDataResponse
}

export const getPutColumnsByIdWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putColumnsByIdWithFormData>>,
    TError,
    { id: string; data: PutColumnsByIdWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putColumnsByIdWithFormData>>,
  TError,
  { id: string; data: PutColumnsByIdWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['putColumnsByIdWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putColumnsByIdWithFormData>>,
    { id: string; data: PutColumnsByIdWithFormDataBodyThree }
  > = (props) => {
    const { id, data } = props ?? {}

    return putColumnsByIdWithFormData(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutColumnsByIdWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof putColumnsByIdWithFormData>>
>
export type PutColumnsByIdWithFormDataMutationBody =
  PutColumnsByIdWithFormDataBodyThree
export type PutColumnsByIdWithFormDataMutationError = unknown

export const usePutColumnsByIdWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putColumnsByIdWithFormData>>,
      TError,
      { id: string; data: PutColumnsByIdWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putColumnsByIdWithFormData>>,
  TError,
  { id: string; data: PutColumnsByIdWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPutColumnsByIdWithFormDataMutationOptions(options),
    queryClient,
  )
}
export type deleteColumnsByIdResponse200 = {
  data: void
  status: 200
}

export type deleteColumnsByIdResponseSuccess = deleteColumnsByIdResponse200 & {
  headers: Headers
}

export type deleteColumnsByIdResponse = deleteColumnsByIdResponseSuccess

export const getDeleteColumnsByIdUrl = (id: string) => {
  return `http://localhost:3333/columns/${id}`
}

export const deleteColumnsById = async (
  id: string,
  options?: RequestInit,
): Promise<deleteColumnsByIdResponse> => {
  const res = await fetch(getDeleteColumnsByIdUrl(id), {
    credentials: 'include',
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: deleteColumnsByIdResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteColumnsByIdResponse
}

export const getDeleteColumnsByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteColumnsById>>,
    TError,
    { id: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteColumnsById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteColumnsById']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteColumnsById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteColumnsById(id, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteColumnsByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteColumnsById>>
>

export type DeleteColumnsByIdMutationError = unknown

export const useDeleteColumnsById = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteColumnsById>>,
      TError,
      { id: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteColumnsById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteColumnsByIdMutationOptions(options), queryClient)
}
