/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  GetProjects200Item,
  PostProjectsWithFormDataBodyThree,
  PostProjectsWithJsonBodyOne,
  PostProjectsWithUrlEncodedBodyTwo,
} from './model'

/**
 * Create a new project
 */
export type postProjectsWithJsonResponse201 = {
  data: void
  status: 201
}

export type postProjectsWithJsonResponseSuccess =
  postProjectsWithJsonResponse201 & {
    headers: Headers
  }

export type postProjectsWithJsonResponse = postProjectsWithJsonResponseSuccess

export const getPostProjectsWithJsonUrl = () => {
  return `http://localhost:3333/projects`
}

export const postProjectsWithJson = async (
  postProjectsWithJsonBodyOne: PostProjectsWithJsonBodyOne,
  options?: RequestInit,
): Promise<postProjectsWithJsonResponse> => {
  const res = await fetch(getPostProjectsWithJsonUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postProjectsWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postProjectsWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postProjectsWithJsonResponse
}

export const getPostProjectsWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProjectsWithJson>>,
    TError,
    { data: PostProjectsWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postProjectsWithJson>>,
  TError,
  { data: PostProjectsWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['postProjectsWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postProjectsWithJson>>,
    { data: PostProjectsWithJsonBodyOne }
  > = (props) => {
    const { data } = props ?? {}

    return postProjectsWithJson(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostProjectsWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postProjectsWithJson>>
>
export type PostProjectsWithJsonMutationBody = PostProjectsWithJsonBodyOne
export type PostProjectsWithJsonMutationError = unknown

export const usePostProjectsWithJson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postProjectsWithJson>>,
      TError,
      { data: PostProjectsWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postProjectsWithJson>>,
  TError,
  { data: PostProjectsWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPostProjectsWithJsonMutationOptions(options),
    queryClient,
  )
}

/**
 * Create a new project
 */
export type postProjectsWithUrlEncodedResponse201 = {
  data: void
  status: 201
}

export type postProjectsWithUrlEncodedResponseSuccess =
  postProjectsWithUrlEncodedResponse201 & {
    headers: Headers
  }

export type postProjectsWithUrlEncodedResponse =
  postProjectsWithUrlEncodedResponseSuccess

export const getPostProjectsWithUrlEncodedUrl = () => {
  return `http://localhost:3333/projects`
}

export const postProjectsWithUrlEncoded = async (
  postProjectsWithUrlEncodedBodyTwo: PostProjectsWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<postProjectsWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(`name`, postProjectsWithUrlEncodedBodyTwo.name)

  const res = await fetch(getPostProjectsWithUrlEncodedUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postProjectsWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postProjectsWithUrlEncodedResponse
}

export const getPostProjectsWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>,
    TError,
    { data: PostProjectsWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>,
  TError,
  { data: PostProjectsWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['postProjectsWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>,
    { data: PostProjectsWithUrlEncodedBodyTwo }
  > = (props) => {
    const { data } = props ?? {}

    return postProjectsWithUrlEncoded(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostProjectsWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>
>
export type PostProjectsWithUrlEncodedMutationBody =
  PostProjectsWithUrlEncodedBodyTwo
export type PostProjectsWithUrlEncodedMutationError = unknown

export const usePostProjectsWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>,
      TError,
      { data: PostProjectsWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>,
  TError,
  { data: PostProjectsWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPostProjectsWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}

/**
 * Create a new project
 */
export type postProjectsWithFormDataResponse201 = {
  data: void
  status: 201
}

export type postProjectsWithFormDataResponseSuccess =
  postProjectsWithFormDataResponse201 & {
    headers: Headers
  }

export type postProjectsWithFormDataResponse =
  postProjectsWithFormDataResponseSuccess

export const getPostProjectsWithFormDataUrl = () => {
  return `http://localhost:3333/projects`
}

export const postProjectsWithFormData = async (
  postProjectsWithFormDataBodyThree: PostProjectsWithFormDataBodyThree,
  options?: RequestInit,
): Promise<postProjectsWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(`name`, postProjectsWithFormDataBodyThree.name)

  const res = await fetch(getPostProjectsWithFormDataUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postProjectsWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postProjectsWithFormDataResponse
}

export const getPostProjectsWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProjectsWithFormData>>,
    TError,
    { data: PostProjectsWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postProjectsWithFormData>>,
  TError,
  { data: PostProjectsWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['postProjectsWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postProjectsWithFormData>>,
    { data: PostProjectsWithFormDataBodyThree }
  > = (props) => {
    const { data } = props ?? {}

    return postProjectsWithFormData(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostProjectsWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof postProjectsWithFormData>>
>
export type PostProjectsWithFormDataMutationBody =
  PostProjectsWithFormDataBodyThree
export type PostProjectsWithFormDataMutationError = unknown

export const usePostProjectsWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postProjectsWithFormData>>,
      TError,
      { data: PostProjectsWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postProjectsWithFormData>>,
  TError,
  { data: PostProjectsWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPostProjectsWithFormDataMutationOptions(options),
    queryClient,
  )
}

/**
 * Get all projects
 */
export type getProjectsResponse200 = {
  data: GetProjects200Item[]
  status: 200
}

export type getProjectsResponseSuccess = getProjectsResponse200 & {
  headers: Headers
}

export type getProjectsResponse = getProjectsResponseSuccess

export const getGetProjectsUrl = () => {
  return `http://localhost:3333/projects`
}

export const getProjects = async (
  options?: RequestInit,
): Promise<getProjectsResponse> => {
  const res = await fetch(getGetProjectsUrl(), {
    credentials: 'include',
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getProjectsResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getProjectsResponse
}

export const getGetProjectsQueryKey = () => {
  return [`http://localhost:3333/projects`] as const
}

export const getGetProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
  >
  fetch?: RequestInit
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetProjectsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjects>>> = ({
    signal,
  }) => getProjects({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjects>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjects>>
>
export type GetProjectsQueryError = unknown

export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetProjectsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
