/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  GetLabelsByProjectId200,
  GetLabelsByProjectIdParams,
  PostLabelsWithFormData201,
  PostLabelsWithFormDataBodyThree,
  PostLabelsWithJson201,
  PostLabelsWithJsonBodyOne,
  PostLabelsWithUrlEncoded201,
  PostLabelsWithUrlEncodedBodyTwo,
  PutLabelsByIdWithFormDataBodyThree,
  PutLabelsByIdWithJsonBodyOne,
  PutLabelsByIdWithUrlEncodedBodyTwo,
} from './model'

/**
 * Create a new label
 */
export type postLabelsWithJsonResponse201 = {
  data: PostLabelsWithJson201
  status: 201
}

export type postLabelsWithJsonResponseSuccess =
  postLabelsWithJsonResponse201 & {
    headers: Headers
  }

export type postLabelsWithJsonResponse = postLabelsWithJsonResponseSuccess

export const getPostLabelsWithJsonUrl = () => {
  return `http://localhost:3333/labels/`
}

export const postLabelsWithJson = async (
  postLabelsWithJsonBodyOne: PostLabelsWithJsonBodyOne,
  options?: RequestInit,
): Promise<postLabelsWithJsonResponse> => {
  const res = await fetch(getPostLabelsWithJsonUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postLabelsWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postLabelsWithJsonResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postLabelsWithJsonResponse
}

export const getPostLabelsWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postLabelsWithJson>>,
    TError,
    { data: PostLabelsWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postLabelsWithJson>>,
  TError,
  { data: PostLabelsWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['postLabelsWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postLabelsWithJson>>,
    { data: PostLabelsWithJsonBodyOne }
  > = (props) => {
    const { data } = props ?? {}

    return postLabelsWithJson(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostLabelsWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postLabelsWithJson>>
>
export type PostLabelsWithJsonMutationBody = PostLabelsWithJsonBodyOne
export type PostLabelsWithJsonMutationError = unknown

export const usePostLabelsWithJson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postLabelsWithJson>>,
      TError,
      { data: PostLabelsWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postLabelsWithJson>>,
  TError,
  { data: PostLabelsWithJsonBodyOne },
  TContext
> => {
  return useMutation(getPostLabelsWithJsonMutationOptions(options), queryClient)
}
/**
 * Create a new label
 */
export type postLabelsWithUrlEncodedResponse201 = {
  data: PostLabelsWithUrlEncoded201
  status: 201
}

export type postLabelsWithUrlEncodedResponseSuccess =
  postLabelsWithUrlEncodedResponse201 & {
    headers: Headers
  }

export type postLabelsWithUrlEncodedResponse =
  postLabelsWithUrlEncodedResponseSuccess

export const getPostLabelsWithUrlEncodedUrl = () => {
  return `http://localhost:3333/labels/`
}

export const postLabelsWithUrlEncoded = async (
  postLabelsWithUrlEncodedBodyTwo: PostLabelsWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<postLabelsWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(`name`, postLabelsWithUrlEncodedBodyTwo.name)
  formUrlEncoded.append(`color`, postLabelsWithUrlEncodedBodyTwo.color)
  formUrlEncoded.append(`projectId`, postLabelsWithUrlEncodedBodyTwo.projectId)

  const res = await fetch(getPostLabelsWithUrlEncodedUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postLabelsWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postLabelsWithUrlEncodedResponse
}

export const getPostLabelsWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postLabelsWithUrlEncoded>>,
    TError,
    { data: PostLabelsWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postLabelsWithUrlEncoded>>,
  TError,
  { data: PostLabelsWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['postLabelsWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postLabelsWithUrlEncoded>>,
    { data: PostLabelsWithUrlEncodedBodyTwo }
  > = (props) => {
    const { data } = props ?? {}

    return postLabelsWithUrlEncoded(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostLabelsWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof postLabelsWithUrlEncoded>>
>
export type PostLabelsWithUrlEncodedMutationBody =
  PostLabelsWithUrlEncodedBodyTwo
export type PostLabelsWithUrlEncodedMutationError = unknown

export const usePostLabelsWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postLabelsWithUrlEncoded>>,
      TError,
      { data: PostLabelsWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postLabelsWithUrlEncoded>>,
  TError,
  { data: PostLabelsWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPostLabelsWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
/**
 * Create a new label
 */
export type postLabelsWithFormDataResponse201 = {
  data: PostLabelsWithFormData201
  status: 201
}

export type postLabelsWithFormDataResponseSuccess =
  postLabelsWithFormDataResponse201 & {
    headers: Headers
  }

export type postLabelsWithFormDataResponse =
  postLabelsWithFormDataResponseSuccess

export const getPostLabelsWithFormDataUrl = () => {
  return `http://localhost:3333/labels/`
}

export const postLabelsWithFormData = async (
  postLabelsWithFormDataBodyThree: PostLabelsWithFormDataBodyThree,
  options?: RequestInit,
): Promise<postLabelsWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(`name`, postLabelsWithFormDataBodyThree.name)
  formData.append(`color`, postLabelsWithFormDataBodyThree.color)
  formData.append(`projectId`, postLabelsWithFormDataBodyThree.projectId)

  const res = await fetch(getPostLabelsWithFormDataUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postLabelsWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postLabelsWithFormDataResponse
}

export const getPostLabelsWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postLabelsWithFormData>>,
    TError,
    { data: PostLabelsWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postLabelsWithFormData>>,
  TError,
  { data: PostLabelsWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['postLabelsWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postLabelsWithFormData>>,
    { data: PostLabelsWithFormDataBodyThree }
  > = (props) => {
    const { data } = props ?? {}

    return postLabelsWithFormData(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostLabelsWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof postLabelsWithFormData>>
>
export type PostLabelsWithFormDataMutationBody = PostLabelsWithFormDataBodyThree
export type PostLabelsWithFormDataMutationError = unknown

export const usePostLabelsWithFormData = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postLabelsWithFormData>>,
      TError,
      { data: PostLabelsWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postLabelsWithFormData>>,
  TError,
  { data: PostLabelsWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPostLabelsWithFormDataMutationOptions(options),
    queryClient,
  )
}
/**
 * Get all labels
 */
export type getLabelsByProjectIdResponse200 = {
  data: GetLabelsByProjectId200
  status: 200
}

export type getLabelsByProjectIdResponseSuccess =
  getLabelsByProjectIdResponse200 & {
    headers: Headers
  }

export type getLabelsByProjectIdResponse = getLabelsByProjectIdResponseSuccess

export const getGetLabelsByProjectIdUrl = (
  projectId: string,
  params?: GetLabelsByProjectIdParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://localhost:3333/labels/${projectId}?${stringifiedParams}`
    : `http://localhost:3333/labels/${projectId}`
}

export const getLabelsByProjectId = async (
  projectId: string,
  params?: GetLabelsByProjectIdParams,
  options?: RequestInit,
): Promise<getLabelsByProjectIdResponse> => {
  const res = await fetch(getGetLabelsByProjectIdUrl(projectId, params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getLabelsByProjectIdResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getLabelsByProjectIdResponse
}

export const getGetLabelsByProjectIdQueryKey = (
  projectId: string,
  params?: GetLabelsByProjectIdParams,
) => {
  return [
    `http://localhost:3333/labels/${projectId}`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetLabelsByProjectIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getLabelsByProjectId>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetLabelsByProjectIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLabelsByProjectId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetLabelsByProjectIdQueryKey(projectId, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLabelsByProjectId>>
  > = ({ signal }) =>
    getLabelsByProjectId(projectId, params, { signal, ...fetchOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getLabelsByProjectId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLabelsByProjectIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLabelsByProjectId>>
>
export type GetLabelsByProjectIdQueryError = unknown

export function useGetLabelsByProjectId<
  TData = Awaited<ReturnType<typeof getLabelsByProjectId>>,
  TError = unknown,
>(
  projectId: string,
  params: undefined | GetLabelsByProjectIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLabelsByProjectId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabelsByProjectId>>,
          TError,
          Awaited<ReturnType<typeof getLabelsByProjectId>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetLabelsByProjectId<
  TData = Awaited<ReturnType<typeof getLabelsByProjectId>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetLabelsByProjectIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLabelsByProjectId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabelsByProjectId>>,
          TError,
          Awaited<ReturnType<typeof getLabelsByProjectId>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetLabelsByProjectId<
  TData = Awaited<ReturnType<typeof getLabelsByProjectId>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetLabelsByProjectIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLabelsByProjectId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetLabelsByProjectId<
  TData = Awaited<ReturnType<typeof getLabelsByProjectId>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetLabelsByProjectIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLabelsByProjectId>>,
        TError,
        TData
      >
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetLabelsByProjectIdQueryOptions(
    projectId,
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Update a label
 */
export type putLabelsByIdWithJsonResponse200 = {
  data: void
  status: 200
}

export type putLabelsByIdWithJsonResponseSuccess =
  putLabelsByIdWithJsonResponse200 & {
    headers: Headers
  }

export type putLabelsByIdWithJsonResponse = putLabelsByIdWithJsonResponseSuccess

export const getPutLabelsByIdWithJsonUrl = (id: string) => {
  return `http://localhost:3333/labels/${id}`
}

export const putLabelsByIdWithJson = async (
  id: string,
  putLabelsByIdWithJsonBodyOne: PutLabelsByIdWithJsonBodyOne,
  options?: RequestInit,
): Promise<putLabelsByIdWithJsonResponse> => {
  const res = await fetch(getPutLabelsByIdWithJsonUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putLabelsByIdWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putLabelsByIdWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putLabelsByIdWithJsonResponse
}

export const getPutLabelsByIdWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putLabelsByIdWithJson>>,
    TError,
    { id: string; data: PutLabelsByIdWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putLabelsByIdWithJson>>,
  TError,
  { id: string; data: PutLabelsByIdWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['putLabelsByIdWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putLabelsByIdWithJson>>,
    { id: string; data: PutLabelsByIdWithJsonBodyOne }
  > = (props) => {
    const { id, data } = props ?? {}

    return putLabelsByIdWithJson(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutLabelsByIdWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof putLabelsByIdWithJson>>
>
export type PutLabelsByIdWithJsonMutationBody = PutLabelsByIdWithJsonBodyOne
export type PutLabelsByIdWithJsonMutationError = unknown

export const usePutLabelsByIdWithJson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putLabelsByIdWithJson>>,
      TError,
      { id: string; data: PutLabelsByIdWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putLabelsByIdWithJson>>,
  TError,
  { id: string; data: PutLabelsByIdWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPutLabelsByIdWithJsonMutationOptions(options),
    queryClient,
  )
}
/**
 * Update a label
 */
export type putLabelsByIdWithUrlEncodedResponse200 = {
  data: void
  status: 200
}

export type putLabelsByIdWithUrlEncodedResponseSuccess =
  putLabelsByIdWithUrlEncodedResponse200 & {
    headers: Headers
  }

export type putLabelsByIdWithUrlEncodedResponse =
  putLabelsByIdWithUrlEncodedResponseSuccess

export const getPutLabelsByIdWithUrlEncodedUrl = (id: string) => {
  return `http://localhost:3333/labels/${id}`
}

export const putLabelsByIdWithUrlEncoded = async (
  id: string,
  putLabelsByIdWithUrlEncodedBodyTwo: PutLabelsByIdWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<putLabelsByIdWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(`name`, putLabelsByIdWithUrlEncodedBodyTwo.name)
  formUrlEncoded.append(`color`, putLabelsByIdWithUrlEncodedBodyTwo.color)

  const res = await fetch(getPutLabelsByIdWithUrlEncodedUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putLabelsByIdWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putLabelsByIdWithUrlEncodedResponse
}

export const getPutLabelsByIdWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putLabelsByIdWithUrlEncoded>>,
    TError,
    { id: string; data: PutLabelsByIdWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putLabelsByIdWithUrlEncoded>>,
  TError,
  { id: string; data: PutLabelsByIdWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['putLabelsByIdWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putLabelsByIdWithUrlEncoded>>,
    { id: string; data: PutLabelsByIdWithUrlEncodedBodyTwo }
  > = (props) => {
    const { id, data } = props ?? {}

    return putLabelsByIdWithUrlEncoded(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutLabelsByIdWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof putLabelsByIdWithUrlEncoded>>
>
export type PutLabelsByIdWithUrlEncodedMutationBody =
  PutLabelsByIdWithUrlEncodedBodyTwo
export type PutLabelsByIdWithUrlEncodedMutationError = unknown

export const usePutLabelsByIdWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putLabelsByIdWithUrlEncoded>>,
      TError,
      { id: string; data: PutLabelsByIdWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putLabelsByIdWithUrlEncoded>>,
  TError,
  { id: string; data: PutLabelsByIdWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPutLabelsByIdWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
/**
 * Update a label
 */
export type putLabelsByIdWithFormDataResponse200 = {
  data: void
  status: 200
}

export type putLabelsByIdWithFormDataResponseSuccess =
  putLabelsByIdWithFormDataResponse200 & {
    headers: Headers
  }

export type putLabelsByIdWithFormDataResponse =
  putLabelsByIdWithFormDataResponseSuccess

export const getPutLabelsByIdWithFormDataUrl = (id: string) => {
  return `http://localhost:3333/labels/${id}`
}

export const putLabelsByIdWithFormData = async (
  id: string,
  putLabelsByIdWithFormDataBodyThree: PutLabelsByIdWithFormDataBodyThree,
  options?: RequestInit,
): Promise<putLabelsByIdWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(`name`, putLabelsByIdWithFormDataBodyThree.name)
  formData.append(`color`, putLabelsByIdWithFormDataBodyThree.color)

  const res = await fetch(getPutLabelsByIdWithFormDataUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putLabelsByIdWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putLabelsByIdWithFormDataResponse
}

export const getPutLabelsByIdWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putLabelsByIdWithFormData>>,
    TError,
    { id: string; data: PutLabelsByIdWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putLabelsByIdWithFormData>>,
  TError,
  { id: string; data: PutLabelsByIdWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['putLabelsByIdWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putLabelsByIdWithFormData>>,
    { id: string; data: PutLabelsByIdWithFormDataBodyThree }
  > = (props) => {
    const { id, data } = props ?? {}

    return putLabelsByIdWithFormData(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutLabelsByIdWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof putLabelsByIdWithFormData>>
>
export type PutLabelsByIdWithFormDataMutationBody =
  PutLabelsByIdWithFormDataBodyThree
export type PutLabelsByIdWithFormDataMutationError = unknown

export const usePutLabelsByIdWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putLabelsByIdWithFormData>>,
      TError,
      { id: string; data: PutLabelsByIdWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putLabelsByIdWithFormData>>,
  TError,
  { id: string; data: PutLabelsByIdWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPutLabelsByIdWithFormDataMutationOptions(options),
    queryClient,
  )
}
/**
 * Delete label
 */
export type deleteLabelsByIdResponse200 = {
  data: void
  status: 200
}

export type deleteLabelsByIdResponseSuccess = deleteLabelsByIdResponse200 & {
  headers: Headers
}

export type deleteLabelsByIdResponse = deleteLabelsByIdResponseSuccess

export const getDeleteLabelsByIdUrl = (id: string) => {
  return `http://localhost:3333/labels/${id}`
}

export const deleteLabelsById = async (
  id: string,
  options?: RequestInit,
): Promise<deleteLabelsByIdResponse> => {
  const res = await fetch(getDeleteLabelsByIdUrl(id), {
    credentials: 'include',
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: deleteLabelsByIdResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteLabelsByIdResponse
}

export const getDeleteLabelsByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteLabelsById>>,
    TError,
    { id: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteLabelsById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteLabelsById']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteLabelsById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteLabelsById(id, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteLabelsByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteLabelsById>>
>

export type DeleteLabelsByIdMutationError = unknown

export const useDeleteLabelsById = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteLabelsById>>,
      TError,
      { id: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteLabelsById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteLabelsByIdMutationOptions(options), queryClient)
}
