/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  GetProjects200,
  GetProjectsParams,
  PostProjectsWithFormData201,
  PostProjectsWithFormDataBodyThree,
  PostProjectsWithJson201,
  PostProjectsWithJsonBodyOne,
  PostProjectsWithUrlEncoded201,
  PostProjectsWithUrlEncodedBodyTwo,
  PutProjectsByIdWithFormDataBodyThree,
  PutProjectsByIdWithJsonBodyOne,
  PutProjectsByIdWithUrlEncodedBodyTwo,
} from './model'

/**
 * Create a new project
 */
export type postProjectsWithJsonResponse201 = {
  data: PostProjectsWithJson201
  status: 201
}

export type postProjectsWithJsonResponseSuccess =
  postProjectsWithJsonResponse201 & {
    headers: Headers
  }

export type postProjectsWithJsonResponse = postProjectsWithJsonResponseSuccess

export const getPostProjectsWithJsonUrl = () => {
  return `http://localhost:3333/projects`
}

export const postProjectsWithJson = async (
  postProjectsWithJsonBodyOne: PostProjectsWithJsonBodyOne,
  options?: RequestInit,
): Promise<postProjectsWithJsonResponse> => {
  const res = await fetch(getPostProjectsWithJsonUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postProjectsWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postProjectsWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postProjectsWithJsonResponse
}

export const getPostProjectsWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProjectsWithJson>>,
    TError,
    { data: PostProjectsWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postProjectsWithJson>>,
  TError,
  { data: PostProjectsWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['postProjectsWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postProjectsWithJson>>,
    { data: PostProjectsWithJsonBodyOne }
  > = (props) => {
    const { data } = props ?? {}

    return postProjectsWithJson(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostProjectsWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postProjectsWithJson>>
>
export type PostProjectsWithJsonMutationBody = PostProjectsWithJsonBodyOne
export type PostProjectsWithJsonMutationError = unknown

export const usePostProjectsWithJson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postProjectsWithJson>>,
      TError,
      { data: PostProjectsWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postProjectsWithJson>>,
  TError,
  { data: PostProjectsWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPostProjectsWithJsonMutationOptions(options),
    queryClient,
  )
}
/**
 * Create a new project
 */
export type postProjectsWithUrlEncodedResponse201 = {
  data: PostProjectsWithUrlEncoded201
  status: 201
}

export type postProjectsWithUrlEncodedResponseSuccess =
  postProjectsWithUrlEncodedResponse201 & {
    headers: Headers
  }

export type postProjectsWithUrlEncodedResponse =
  postProjectsWithUrlEncodedResponseSuccess

export const getPostProjectsWithUrlEncodedUrl = () => {
  return `http://localhost:3333/projects`
}

export const postProjectsWithUrlEncoded = async (
  postProjectsWithUrlEncodedBodyTwo: PostProjectsWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<postProjectsWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(`name`, postProjectsWithUrlEncodedBodyTwo.name)

  const res = await fetch(getPostProjectsWithUrlEncodedUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postProjectsWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postProjectsWithUrlEncodedResponse
}

export const getPostProjectsWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>,
    TError,
    { data: PostProjectsWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>,
  TError,
  { data: PostProjectsWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['postProjectsWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>,
    { data: PostProjectsWithUrlEncodedBodyTwo }
  > = (props) => {
    const { data } = props ?? {}

    return postProjectsWithUrlEncoded(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostProjectsWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>
>
export type PostProjectsWithUrlEncodedMutationBody =
  PostProjectsWithUrlEncodedBodyTwo
export type PostProjectsWithUrlEncodedMutationError = unknown

export const usePostProjectsWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>,
      TError,
      { data: PostProjectsWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postProjectsWithUrlEncoded>>,
  TError,
  { data: PostProjectsWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPostProjectsWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
/**
 * Create a new project
 */
export type postProjectsWithFormDataResponse201 = {
  data: PostProjectsWithFormData201
  status: 201
}

export type postProjectsWithFormDataResponseSuccess =
  postProjectsWithFormDataResponse201 & {
    headers: Headers
  }

export type postProjectsWithFormDataResponse =
  postProjectsWithFormDataResponseSuccess

export const getPostProjectsWithFormDataUrl = () => {
  return `http://localhost:3333/projects`
}

export const postProjectsWithFormData = async (
  postProjectsWithFormDataBodyThree: PostProjectsWithFormDataBodyThree,
  options?: RequestInit,
): Promise<postProjectsWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(`name`, postProjectsWithFormDataBodyThree.name)

  const res = await fetch(getPostProjectsWithFormDataUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postProjectsWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postProjectsWithFormDataResponse
}

export const getPostProjectsWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProjectsWithFormData>>,
    TError,
    { data: PostProjectsWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postProjectsWithFormData>>,
  TError,
  { data: PostProjectsWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['postProjectsWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postProjectsWithFormData>>,
    { data: PostProjectsWithFormDataBodyThree }
  > = (props) => {
    const { data } = props ?? {}

    return postProjectsWithFormData(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostProjectsWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof postProjectsWithFormData>>
>
export type PostProjectsWithFormDataMutationBody =
  PostProjectsWithFormDataBodyThree
export type PostProjectsWithFormDataMutationError = unknown

export const usePostProjectsWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postProjectsWithFormData>>,
      TError,
      { data: PostProjectsWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postProjectsWithFormData>>,
  TError,
  { data: PostProjectsWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPostProjectsWithFormDataMutationOptions(options),
    queryClient,
  )
}
/**
 * Get all projects
 */
export type getProjectsResponse200 = {
  data: GetProjects200
  status: 200
}

export type getProjectsResponseSuccess = getProjectsResponse200 & {
  headers: Headers
}

export type getProjectsResponse = getProjectsResponseSuccess

export const getGetProjectsUrl = (params?: GetProjectsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://localhost:3333/projects?${stringifiedParams}`
    : `http://localhost:3333/projects`
}

export const getProjects = async (
  params?: GetProjectsParams,
  options?: RequestInit,
): Promise<getProjectsResponse> => {
  const res = await fetch(getGetProjectsUrl(params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getProjectsResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getProjectsResponse
}

export const getGetProjectsQueryKey = (params?: GetProjectsParams) => {
  return [
    `http://localhost:3333/projects`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = unknown,
>(
  params?: GetProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetProjectsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjects>>> = ({
    signal,
  }) => getProjects(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjects>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjects>>
>
export type GetProjectsQueryError = unknown

export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = unknown,
>(
  params: undefined | GetProjectsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = unknown,
>(
  params?: GetProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = unknown,
>(
  params?: GetProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = unknown,
>(
  params?: GetProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetProjectsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Delete project
 */
export type deleteProjectsByIdResponse200 = {
  data: void
  status: 200
}

export type deleteProjectsByIdResponseSuccess =
  deleteProjectsByIdResponse200 & {
    headers: Headers
  }

export type deleteProjectsByIdResponse = deleteProjectsByIdResponseSuccess

export const getDeleteProjectsByIdUrl = (id: string) => {
  return `http://localhost:3333/projects/${id}`
}

export const deleteProjectsById = async (
  id: string,
  options?: RequestInit,
): Promise<deleteProjectsByIdResponse> => {
  const res = await fetch(getDeleteProjectsByIdUrl(id), {
    credentials: 'include',
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: deleteProjectsByIdResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteProjectsByIdResponse
}

export const getDeleteProjectsByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProjectsById>>,
    TError,
    { id: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteProjectsById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteProjectsById']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProjectsById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteProjectsById(id, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteProjectsByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteProjectsById>>
>

export type DeleteProjectsByIdMutationError = unknown

export const useDeleteProjectsById = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteProjectsById>>,
      TError,
      { id: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteProjectsById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteProjectsByIdMutationOptions(options), queryClient)
}
/**
 * Update a project
 */
export type putProjectsByIdWithJsonResponse200 = {
  data: void
  status: 200
}

export type putProjectsByIdWithJsonResponseSuccess =
  putProjectsByIdWithJsonResponse200 & {
    headers: Headers
  }

export type putProjectsByIdWithJsonResponse =
  putProjectsByIdWithJsonResponseSuccess

export const getPutProjectsByIdWithJsonUrl = (id: string) => {
  return `http://localhost:3333/projects/${id}`
}

export const putProjectsByIdWithJson = async (
  id: string,
  putProjectsByIdWithJsonBodyOne: PutProjectsByIdWithJsonBodyOne,
  options?: RequestInit,
): Promise<putProjectsByIdWithJsonResponse> => {
  const res = await fetch(getPutProjectsByIdWithJsonUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putProjectsByIdWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putProjectsByIdWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putProjectsByIdWithJsonResponse
}

export const getPutProjectsByIdWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putProjectsByIdWithJson>>,
    TError,
    { id: string; data: PutProjectsByIdWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putProjectsByIdWithJson>>,
  TError,
  { id: string; data: PutProjectsByIdWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['putProjectsByIdWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putProjectsByIdWithJson>>,
    { id: string; data: PutProjectsByIdWithJsonBodyOne }
  > = (props) => {
    const { id, data } = props ?? {}

    return putProjectsByIdWithJson(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutProjectsByIdWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof putProjectsByIdWithJson>>
>
export type PutProjectsByIdWithJsonMutationBody = PutProjectsByIdWithJsonBodyOne
export type PutProjectsByIdWithJsonMutationError = unknown

export const usePutProjectsByIdWithJson = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putProjectsByIdWithJson>>,
      TError,
      { id: string; data: PutProjectsByIdWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putProjectsByIdWithJson>>,
  TError,
  { id: string; data: PutProjectsByIdWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPutProjectsByIdWithJsonMutationOptions(options),
    queryClient,
  )
}
/**
 * Update a project
 */
export type putProjectsByIdWithUrlEncodedResponse200 = {
  data: void
  status: 200
}

export type putProjectsByIdWithUrlEncodedResponseSuccess =
  putProjectsByIdWithUrlEncodedResponse200 & {
    headers: Headers
  }

export type putProjectsByIdWithUrlEncodedResponse =
  putProjectsByIdWithUrlEncodedResponseSuccess

export const getPutProjectsByIdWithUrlEncodedUrl = (id: string) => {
  return `http://localhost:3333/projects/${id}`
}

export const putProjectsByIdWithUrlEncoded = async (
  id: string,
  putProjectsByIdWithUrlEncodedBodyTwo: PutProjectsByIdWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<putProjectsByIdWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(`name`, putProjectsByIdWithUrlEncodedBodyTwo.name)

  const res = await fetch(getPutProjectsByIdWithUrlEncodedUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putProjectsByIdWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putProjectsByIdWithUrlEncodedResponse
}

export const getPutProjectsByIdWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putProjectsByIdWithUrlEncoded>>,
    TError,
    { id: string; data: PutProjectsByIdWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putProjectsByIdWithUrlEncoded>>,
  TError,
  { id: string; data: PutProjectsByIdWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['putProjectsByIdWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putProjectsByIdWithUrlEncoded>>,
    { id: string; data: PutProjectsByIdWithUrlEncodedBodyTwo }
  > = (props) => {
    const { id, data } = props ?? {}

    return putProjectsByIdWithUrlEncoded(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutProjectsByIdWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof putProjectsByIdWithUrlEncoded>>
>
export type PutProjectsByIdWithUrlEncodedMutationBody =
  PutProjectsByIdWithUrlEncodedBodyTwo
export type PutProjectsByIdWithUrlEncodedMutationError = unknown

export const usePutProjectsByIdWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putProjectsByIdWithUrlEncoded>>,
      TError,
      { id: string; data: PutProjectsByIdWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putProjectsByIdWithUrlEncoded>>,
  TError,
  { id: string; data: PutProjectsByIdWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPutProjectsByIdWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
/**
 * Update a project
 */
export type putProjectsByIdWithFormDataResponse200 = {
  data: void
  status: 200
}

export type putProjectsByIdWithFormDataResponseSuccess =
  putProjectsByIdWithFormDataResponse200 & {
    headers: Headers
  }

export type putProjectsByIdWithFormDataResponse =
  putProjectsByIdWithFormDataResponseSuccess

export const getPutProjectsByIdWithFormDataUrl = (id: string) => {
  return `http://localhost:3333/projects/${id}`
}

export const putProjectsByIdWithFormData = async (
  id: string,
  putProjectsByIdWithFormDataBodyThree: PutProjectsByIdWithFormDataBodyThree,
  options?: RequestInit,
): Promise<putProjectsByIdWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(`name`, putProjectsByIdWithFormDataBodyThree.name)

  const res = await fetch(getPutProjectsByIdWithFormDataUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putProjectsByIdWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putProjectsByIdWithFormDataResponse
}

export const getPutProjectsByIdWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putProjectsByIdWithFormData>>,
    TError,
    { id: string; data: PutProjectsByIdWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putProjectsByIdWithFormData>>,
  TError,
  { id: string; data: PutProjectsByIdWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['putProjectsByIdWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putProjectsByIdWithFormData>>,
    { id: string; data: PutProjectsByIdWithFormDataBodyThree }
  > = (props) => {
    const { id, data } = props ?? {}

    return putProjectsByIdWithFormData(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutProjectsByIdWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof putProjectsByIdWithFormData>>
>
export type PutProjectsByIdWithFormDataMutationBody =
  PutProjectsByIdWithFormDataBodyThree
export type PutProjectsByIdWithFormDataMutationError = unknown

export const usePutProjectsByIdWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putProjectsByIdWithFormData>>,
      TError,
      { id: string; data: PutProjectsByIdWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putProjectsByIdWithFormData>>,
  TError,
  { id: string; data: PutProjectsByIdWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPutProjectsByIdWithFormDataMutationOptions(options),
    queryClient,
  )
}
