/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'

import type {
  GetTasks200,
  GetTasksParams,
  PatchTasksReorderWithFormDataBodyThree,
  PatchTasksReorderWithJsonBodyOne,
  PatchTasksReorderWithUrlEncodedBodyTwo,
  PostTasksWithFormData201,
  PostTasksWithFormDataBodyThree,
  PostTasksWithJson201,
  PostTasksWithJsonBodyOne,
  PostTasksWithUrlEncoded201,
  PostTasksWithUrlEncodedBodyTwo,
  PutTasksByIdWithFormData200,
  PutTasksByIdWithFormDataBodyThree,
  PutTasksByIdWithJson200,
  PutTasksByIdWithJsonBodyOne,
  PutTasksByIdWithUrlEncoded200,
  PutTasksByIdWithUrlEncodedBodyTwo,
} from './model'

export type postTasksWithJsonResponse201 = {
  data: PostTasksWithJson201
  status: 201
}

export type postTasksWithJsonResponseSuccess = postTasksWithJsonResponse201 & {
  headers: Headers
}

export type postTasksWithJsonResponse = postTasksWithJsonResponseSuccess

export const getPostTasksWithJsonUrl = () => {
  return `http://localhost:3333/tasks/`
}

export const postTasksWithJson = async (
  postTasksWithJsonBodyOne: PostTasksWithJsonBodyOne,
  options?: RequestInit,
): Promise<postTasksWithJsonResponse> => {
  const res = await fetch(getPostTasksWithJsonUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postTasksWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postTasksWithJsonResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postTasksWithJsonResponse
}

export const getPostTasksWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTasksWithJson>>,
    TError,
    { data: PostTasksWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTasksWithJson>>,
  TError,
  { data: PostTasksWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['postTasksWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTasksWithJson>>,
    { data: PostTasksWithJsonBodyOne }
  > = (props) => {
    const { data } = props ?? {}

    return postTasksWithJson(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostTasksWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTasksWithJson>>
>
export type PostTasksWithJsonMutationBody = PostTasksWithJsonBodyOne
export type PostTasksWithJsonMutationError = unknown

export const usePostTasksWithJson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTasksWithJson>>,
      TError,
      { data: PostTasksWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTasksWithJson>>,
  TError,
  { data: PostTasksWithJsonBodyOne },
  TContext
> => {
  return useMutation(getPostTasksWithJsonMutationOptions(options), queryClient)
}
export type postTasksWithUrlEncodedResponse201 = {
  data: PostTasksWithUrlEncoded201
  status: 201
}

export type postTasksWithUrlEncodedResponseSuccess =
  postTasksWithUrlEncodedResponse201 & {
    headers: Headers
  }

export type postTasksWithUrlEncodedResponse =
  postTasksWithUrlEncodedResponseSuccess

export const getPostTasksWithUrlEncodedUrl = () => {
  return `http://localhost:3333/tasks/`
}

export const postTasksWithUrlEncoded = async (
  postTasksWithUrlEncodedBodyTwo: PostTasksWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<postTasksWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  formUrlEncoded.append(`title`, postTasksWithUrlEncodedBodyTwo.title)
  formUrlEncoded.append(`columnId`, postTasksWithUrlEncodedBodyTwo.columnId)
  if (
    postTasksWithUrlEncodedBodyTwo.labelId !== undefined &&
    postTasksWithUrlEncodedBodyTwo.labelId !== null
  ) {
    formUrlEncoded.append(`labelId`, postTasksWithUrlEncodedBodyTwo.labelId)
  }
  if (
    postTasksWithUrlEncodedBodyTwo.assigneeId !== undefined &&
    postTasksWithUrlEncodedBodyTwo.assigneeId !== null
  ) {
    formUrlEncoded.append(
      `assigneeId`,
      postTasksWithUrlEncodedBodyTwo.assigneeId,
    )
  }
  if (postTasksWithUrlEncodedBodyTwo.description !== undefined) {
    formUrlEncoded.append(
      `description`,
      postTasksWithUrlEncodedBodyTwo.description,
    )
  }
  if (
    postTasksWithUrlEncodedBodyTwo.dueDate !== undefined &&
    postTasksWithUrlEncodedBodyTwo.dueDate !== null
  ) {
    formUrlEncoded.append(`dueDate`, postTasksWithUrlEncodedBodyTwo.dueDate)
  }

  const res = await fetch(getPostTasksWithUrlEncodedUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postTasksWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postTasksWithUrlEncodedResponse
}

export const getPostTasksWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTasksWithUrlEncoded>>,
    TError,
    { data: PostTasksWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTasksWithUrlEncoded>>,
  TError,
  { data: PostTasksWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['postTasksWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTasksWithUrlEncoded>>,
    { data: PostTasksWithUrlEncodedBodyTwo }
  > = (props) => {
    const { data } = props ?? {}

    return postTasksWithUrlEncoded(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostTasksWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTasksWithUrlEncoded>>
>
export type PostTasksWithUrlEncodedMutationBody = PostTasksWithUrlEncodedBodyTwo
export type PostTasksWithUrlEncodedMutationError = unknown

export const usePostTasksWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTasksWithUrlEncoded>>,
      TError,
      { data: PostTasksWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTasksWithUrlEncoded>>,
  TError,
  { data: PostTasksWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPostTasksWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
export type postTasksWithFormDataResponse201 = {
  data: PostTasksWithFormData201
  status: 201
}

export type postTasksWithFormDataResponseSuccess =
  postTasksWithFormDataResponse201 & {
    headers: Headers
  }

export type postTasksWithFormDataResponse = postTasksWithFormDataResponseSuccess

export const getPostTasksWithFormDataUrl = () => {
  return `http://localhost:3333/tasks/`
}

export const postTasksWithFormData = async (
  postTasksWithFormDataBodyThree: PostTasksWithFormDataBodyThree,
  options?: RequestInit,
): Promise<postTasksWithFormDataResponse> => {
  const formData = new FormData()
  formData.append(`title`, postTasksWithFormDataBodyThree.title)
  formData.append(`columnId`, postTasksWithFormDataBodyThree.columnId)
  if (
    postTasksWithFormDataBodyThree.labelId !== undefined &&
    postTasksWithFormDataBodyThree.labelId !== null
  ) {
    formData.append(`labelId`, postTasksWithFormDataBodyThree.labelId)
  }
  if (
    postTasksWithFormDataBodyThree.assigneeId !== undefined &&
    postTasksWithFormDataBodyThree.assigneeId !== null
  ) {
    formData.append(`assigneeId`, postTasksWithFormDataBodyThree.assigneeId)
  }
  if (postTasksWithFormDataBodyThree.description !== undefined) {
    formData.append(`description`, postTasksWithFormDataBodyThree.description)
  }
  if (
    postTasksWithFormDataBodyThree.dueDate !== undefined &&
    postTasksWithFormDataBodyThree.dueDate !== null
  ) {
    formData.append(`dueDate`, postTasksWithFormDataBodyThree.dueDate)
  }

  const res = await fetch(getPostTasksWithFormDataUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: postTasksWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postTasksWithFormDataResponse
}

export const getPostTasksWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTasksWithFormData>>,
    TError,
    { data: PostTasksWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTasksWithFormData>>,
  TError,
  { data: PostTasksWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['postTasksWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTasksWithFormData>>,
    { data: PostTasksWithFormDataBodyThree }
  > = (props) => {
    const { data } = props ?? {}

    return postTasksWithFormData(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostTasksWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTasksWithFormData>>
>
export type PostTasksWithFormDataMutationBody = PostTasksWithFormDataBodyThree
export type PostTasksWithFormDataMutationError = unknown

export const usePostTasksWithFormData = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTasksWithFormData>>,
      TError,
      { data: PostTasksWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTasksWithFormData>>,
  TError,
  { data: PostTasksWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPostTasksWithFormDataMutationOptions(options),
    queryClient,
  )
}
export type getTasksResponse200 = {
  data: GetTasks200
  status: 200
}

export type getTasksResponseSuccess = getTasksResponse200 & {
  headers: Headers
}

export type getTasksResponse = getTasksResponseSuccess

export const getGetTasksUrl = (params: GetTasksParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `http://localhost:3333/tasks/?${stringifiedParams}`
    : `http://localhost:3333/tasks/`
}

export const getTasks = async (
  params: GetTasksParams,
  options?: RequestInit,
): Promise<getTasksResponse> => {
  const res = await fetch(getGetTasksUrl(params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getTasksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTasksResponse
}

export const getGetTasksQueryKey = (params?: GetTasksParams) => {
  return [`http://localhost:3333/tasks/`, ...(params ? [params] : [])] as const
}

export const getGetTasksQueryOptions = <
  TData = Awaited<ReturnType<typeof getTasks>>,
  TError = unknown,
>(
  params: GetTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetTasksQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasks>>> = ({
    signal,
  }) => getTasks(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTasks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTasksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTasks>>
>
export type GetTasksQueryError = unknown

export function useGetTasks<
  TData = Awaited<ReturnType<typeof getTasks>>,
  TError = unknown,
>(
  params: GetTasksParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasks>>,
          TError,
          Awaited<ReturnType<typeof getTasks>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTasks<
  TData = Awaited<ReturnType<typeof getTasks>>,
  TError = unknown,
>(
  params: GetTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasks>>,
          TError,
          Awaited<ReturnType<typeof getTasks>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTasks<
  TData = Awaited<ReturnType<typeof getTasks>>,
  TError = unknown,
>(
  params: GetTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetTasks<
  TData = Awaited<ReturnType<typeof getTasks>>,
  TError = unknown,
>(
  params: GetTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetTasksQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type putTasksByIdWithJsonResponse200 = {
  data: PutTasksByIdWithJson200
  status: 200
}

export type putTasksByIdWithJsonResponseSuccess =
  putTasksByIdWithJsonResponse200 & {
    headers: Headers
  }

export type putTasksByIdWithJsonResponse = putTasksByIdWithJsonResponseSuccess

export const getPutTasksByIdWithJsonUrl = (id: string) => {
  return `http://localhost:3333/tasks/${id}`
}

export const putTasksByIdWithJson = async (
  id: string,
  putTasksByIdWithJsonBodyOne: PutTasksByIdWithJsonBodyOne,
  options?: RequestInit,
): Promise<putTasksByIdWithJsonResponse> => {
  const res = await fetch(getPutTasksByIdWithJsonUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putTasksByIdWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putTasksByIdWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putTasksByIdWithJsonResponse
}

export const getPutTasksByIdWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTasksByIdWithJson>>,
    TError,
    { id: string; data: PutTasksByIdWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putTasksByIdWithJson>>,
  TError,
  { id: string; data: PutTasksByIdWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['putTasksByIdWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putTasksByIdWithJson>>,
    { id: string; data: PutTasksByIdWithJsonBodyOne }
  > = (props) => {
    const { id, data } = props ?? {}

    return putTasksByIdWithJson(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutTasksByIdWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof putTasksByIdWithJson>>
>
export type PutTasksByIdWithJsonMutationBody = PutTasksByIdWithJsonBodyOne
export type PutTasksByIdWithJsonMutationError = unknown

export const usePutTasksByIdWithJson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putTasksByIdWithJson>>,
      TError,
      { id: string; data: PutTasksByIdWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putTasksByIdWithJson>>,
  TError,
  { id: string; data: PutTasksByIdWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPutTasksByIdWithJsonMutationOptions(options),
    queryClient,
  )
}
export type putTasksByIdWithUrlEncodedResponse200 = {
  data: PutTasksByIdWithUrlEncoded200
  status: 200
}

export type putTasksByIdWithUrlEncodedResponseSuccess =
  putTasksByIdWithUrlEncodedResponse200 & {
    headers: Headers
  }

export type putTasksByIdWithUrlEncodedResponse =
  putTasksByIdWithUrlEncodedResponseSuccess

export const getPutTasksByIdWithUrlEncodedUrl = (id: string) => {
  return `http://localhost:3333/tasks/${id}`
}

export const putTasksByIdWithUrlEncoded = async (
  id: string,
  putTasksByIdWithUrlEncodedBodyTwo: PutTasksByIdWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<putTasksByIdWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  if (putTasksByIdWithUrlEncodedBodyTwo.title !== undefined) {
    formUrlEncoded.append(`title`, putTasksByIdWithUrlEncodedBodyTwo.title)
  }
  if (putTasksByIdWithUrlEncodedBodyTwo.columnId !== undefined) {
    formUrlEncoded.append(
      `columnId`,
      putTasksByIdWithUrlEncodedBodyTwo.columnId,
    )
  }
  if (
    putTasksByIdWithUrlEncodedBodyTwo.labelId !== undefined &&
    putTasksByIdWithUrlEncodedBodyTwo.labelId !== null
  ) {
    formUrlEncoded.append(`labelId`, putTasksByIdWithUrlEncodedBodyTwo.labelId)
  }
  if (
    putTasksByIdWithUrlEncodedBodyTwo.assigneeId !== undefined &&
    putTasksByIdWithUrlEncodedBodyTwo.assigneeId !== null
  ) {
    formUrlEncoded.append(
      `assigneeId`,
      putTasksByIdWithUrlEncodedBodyTwo.assigneeId,
    )
  }
  if (putTasksByIdWithUrlEncodedBodyTwo.description !== undefined) {
    formUrlEncoded.append(
      `description`,
      putTasksByIdWithUrlEncodedBodyTwo.description,
    )
  }
  if (
    putTasksByIdWithUrlEncodedBodyTwo.dueDate !== undefined &&
    putTasksByIdWithUrlEncodedBodyTwo.dueDate !== null
  ) {
    formUrlEncoded.append(`dueDate`, putTasksByIdWithUrlEncodedBodyTwo.dueDate)
  }
  if (putTasksByIdWithUrlEncodedBodyTwo.order !== undefined) {
    formUrlEncoded.append(
      `order`,
      putTasksByIdWithUrlEncodedBodyTwo.order.toString(),
    )
  }

  const res = await fetch(getPutTasksByIdWithUrlEncodedUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putTasksByIdWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putTasksByIdWithUrlEncodedResponse
}

export const getPutTasksByIdWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTasksByIdWithUrlEncoded>>,
    TError,
    { id: string; data: PutTasksByIdWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putTasksByIdWithUrlEncoded>>,
  TError,
  { id: string; data: PutTasksByIdWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['putTasksByIdWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putTasksByIdWithUrlEncoded>>,
    { id: string; data: PutTasksByIdWithUrlEncodedBodyTwo }
  > = (props) => {
    const { id, data } = props ?? {}

    return putTasksByIdWithUrlEncoded(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutTasksByIdWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof putTasksByIdWithUrlEncoded>>
>
export type PutTasksByIdWithUrlEncodedMutationBody =
  PutTasksByIdWithUrlEncodedBodyTwo
export type PutTasksByIdWithUrlEncodedMutationError = unknown

export const usePutTasksByIdWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putTasksByIdWithUrlEncoded>>,
      TError,
      { id: string; data: PutTasksByIdWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putTasksByIdWithUrlEncoded>>,
  TError,
  { id: string; data: PutTasksByIdWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPutTasksByIdWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
export type putTasksByIdWithFormDataResponse200 = {
  data: PutTasksByIdWithFormData200
  status: 200
}

export type putTasksByIdWithFormDataResponseSuccess =
  putTasksByIdWithFormDataResponse200 & {
    headers: Headers
  }

export type putTasksByIdWithFormDataResponse =
  putTasksByIdWithFormDataResponseSuccess

export const getPutTasksByIdWithFormDataUrl = (id: string) => {
  return `http://localhost:3333/tasks/${id}`
}

export const putTasksByIdWithFormData = async (
  id: string,
  putTasksByIdWithFormDataBodyThree: PutTasksByIdWithFormDataBodyThree,
  options?: RequestInit,
): Promise<putTasksByIdWithFormDataResponse> => {
  const formData = new FormData()
  if (putTasksByIdWithFormDataBodyThree.title !== undefined) {
    formData.append(`title`, putTasksByIdWithFormDataBodyThree.title)
  }
  if (putTasksByIdWithFormDataBodyThree.columnId !== undefined) {
    formData.append(`columnId`, putTasksByIdWithFormDataBodyThree.columnId)
  }
  if (
    putTasksByIdWithFormDataBodyThree.labelId !== undefined &&
    putTasksByIdWithFormDataBodyThree.labelId !== null
  ) {
    formData.append(`labelId`, putTasksByIdWithFormDataBodyThree.labelId)
  }
  if (
    putTasksByIdWithFormDataBodyThree.assigneeId !== undefined &&
    putTasksByIdWithFormDataBodyThree.assigneeId !== null
  ) {
    formData.append(`assigneeId`, putTasksByIdWithFormDataBodyThree.assigneeId)
  }
  if (putTasksByIdWithFormDataBodyThree.description !== undefined) {
    formData.append(
      `description`,
      putTasksByIdWithFormDataBodyThree.description,
    )
  }
  if (
    putTasksByIdWithFormDataBodyThree.dueDate !== undefined &&
    putTasksByIdWithFormDataBodyThree.dueDate !== null
  ) {
    formData.append(`dueDate`, putTasksByIdWithFormDataBodyThree.dueDate)
  }
  if (putTasksByIdWithFormDataBodyThree.order !== undefined) {
    formData.append(`order`, putTasksByIdWithFormDataBodyThree.order.toString())
  }

  const res = await fetch(getPutTasksByIdWithFormDataUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: putTasksByIdWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putTasksByIdWithFormDataResponse
}

export const getPutTasksByIdWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTasksByIdWithFormData>>,
    TError,
    { id: string; data: PutTasksByIdWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof putTasksByIdWithFormData>>,
  TError,
  { id: string; data: PutTasksByIdWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['putTasksByIdWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putTasksByIdWithFormData>>,
    { id: string; data: PutTasksByIdWithFormDataBodyThree }
  > = (props) => {
    const { id, data } = props ?? {}

    return putTasksByIdWithFormData(id, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutTasksByIdWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof putTasksByIdWithFormData>>
>
export type PutTasksByIdWithFormDataMutationBody =
  PutTasksByIdWithFormDataBodyThree
export type PutTasksByIdWithFormDataMutationError = unknown

export const usePutTasksByIdWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putTasksByIdWithFormData>>,
      TError,
      { id: string; data: PutTasksByIdWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putTasksByIdWithFormData>>,
  TError,
  { id: string; data: PutTasksByIdWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPutTasksByIdWithFormDataMutationOptions(options),
    queryClient,
  )
}
export type deleteTasksByIdResponse200 = {
  data: void
  status: 200
}

export type deleteTasksByIdResponseSuccess = deleteTasksByIdResponse200 & {
  headers: Headers
}

export type deleteTasksByIdResponse = deleteTasksByIdResponseSuccess

export const getDeleteTasksByIdUrl = (id: string) => {
  return `http://localhost:3333/tasks/${id}`
}

export const deleteTasksById = async (
  id: string,
  options?: RequestInit,
): Promise<deleteTasksByIdResponse> => {
  const res = await fetch(getDeleteTasksByIdUrl(id), {
    credentials: 'include',
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: deleteTasksByIdResponse['data'] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteTasksByIdResponse
}

export const getDeleteTasksByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTasksById>>,
    TError,
    { id: string },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTasksById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteTasksById']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTasksById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteTasksById(id, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteTasksByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTasksById>>
>

export type DeleteTasksByIdMutationError = unknown

export const useDeleteTasksById = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTasksById>>,
      TError,
      { id: string },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTasksById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteTasksByIdMutationOptions(options), queryClient)
}
export type patchTasksReorderWithJsonResponse200 = {
  data: void
  status: 200
}

export type patchTasksReorderWithJsonResponseSuccess =
  patchTasksReorderWithJsonResponse200 & {
    headers: Headers
  }

export type patchTasksReorderWithJsonResponse =
  patchTasksReorderWithJsonResponseSuccess

export const getPatchTasksReorderWithJsonUrl = () => {
  return `http://localhost:3333/tasks/reorder`
}

export const patchTasksReorderWithJson = async (
  patchTasksReorderWithJsonBodyOne: PatchTasksReorderWithJsonBodyOne,
  options?: RequestInit,
): Promise<patchTasksReorderWithJsonResponse> => {
  const res = await fetch(getPatchTasksReorderWithJsonUrl(), {
    credentials: 'include',
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchTasksReorderWithJsonBodyOne),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: patchTasksReorderWithJsonResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchTasksReorderWithJsonResponse
}

export const getPatchTasksReorderWithJsonMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchTasksReorderWithJson>>,
    TError,
    { data: PatchTasksReorderWithJsonBodyOne },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchTasksReorderWithJson>>,
  TError,
  { data: PatchTasksReorderWithJsonBodyOne },
  TContext
> => {
  const mutationKey = ['patchTasksReorderWithJson']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchTasksReorderWithJson>>,
    { data: PatchTasksReorderWithJsonBodyOne }
  > = (props) => {
    const { data } = props ?? {}

    return patchTasksReorderWithJson(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PatchTasksReorderWithJsonMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchTasksReorderWithJson>>
>
export type PatchTasksReorderWithJsonMutationBody =
  PatchTasksReorderWithJsonBodyOne
export type PatchTasksReorderWithJsonMutationError = unknown

export const usePatchTasksReorderWithJson = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchTasksReorderWithJson>>,
      TError,
      { data: PatchTasksReorderWithJsonBodyOne },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchTasksReorderWithJson>>,
  TError,
  { data: PatchTasksReorderWithJsonBodyOne },
  TContext
> => {
  return useMutation(
    getPatchTasksReorderWithJsonMutationOptions(options),
    queryClient,
  )
}
export type patchTasksReorderWithUrlEncodedResponse200 = {
  data: void
  status: 200
}

export type patchTasksReorderWithUrlEncodedResponseSuccess =
  patchTasksReorderWithUrlEncodedResponse200 & {
    headers: Headers
  }

export type patchTasksReorderWithUrlEncodedResponse =
  patchTasksReorderWithUrlEncodedResponseSuccess

export const getPatchTasksReorderWithUrlEncodedUrl = () => {
  return `http://localhost:3333/tasks/reorder`
}

export const patchTasksReorderWithUrlEncoded = async (
  patchTasksReorderWithUrlEncodedBodyTwo: PatchTasksReorderWithUrlEncodedBodyTwo,
  options?: RequestInit,
): Promise<patchTasksReorderWithUrlEncodedResponse> => {
  const formUrlEncoded = new URLSearchParams()
  patchTasksReorderWithUrlEncodedBodyTwo.tasks.forEach((value) =>
    formUrlEncoded.append(`tasks`, JSON.stringify(value)),
  )

  const res = await fetch(getPatchTasksReorderWithUrlEncodedUrl(), {
    credentials: 'include',
    ...options,
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: patchTasksReorderWithUrlEncodedResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchTasksReorderWithUrlEncodedResponse
}

export const getPatchTasksReorderWithUrlEncodedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchTasksReorderWithUrlEncoded>>,
    TError,
    { data: PatchTasksReorderWithUrlEncodedBodyTwo },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchTasksReorderWithUrlEncoded>>,
  TError,
  { data: PatchTasksReorderWithUrlEncodedBodyTwo },
  TContext
> => {
  const mutationKey = ['patchTasksReorderWithUrlEncoded']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchTasksReorderWithUrlEncoded>>,
    { data: PatchTasksReorderWithUrlEncodedBodyTwo }
  > = (props) => {
    const { data } = props ?? {}

    return patchTasksReorderWithUrlEncoded(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PatchTasksReorderWithUrlEncodedMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchTasksReorderWithUrlEncoded>>
>
export type PatchTasksReorderWithUrlEncodedMutationBody =
  PatchTasksReorderWithUrlEncodedBodyTwo
export type PatchTasksReorderWithUrlEncodedMutationError = unknown

export const usePatchTasksReorderWithUrlEncoded = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchTasksReorderWithUrlEncoded>>,
      TError,
      { data: PatchTasksReorderWithUrlEncodedBodyTwo },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchTasksReorderWithUrlEncoded>>,
  TError,
  { data: PatchTasksReorderWithUrlEncodedBodyTwo },
  TContext
> => {
  return useMutation(
    getPatchTasksReorderWithUrlEncodedMutationOptions(options),
    queryClient,
  )
}
export type patchTasksReorderWithFormDataResponse200 = {
  data: void
  status: 200
}

export type patchTasksReorderWithFormDataResponseSuccess =
  patchTasksReorderWithFormDataResponse200 & {
    headers: Headers
  }

export type patchTasksReorderWithFormDataResponse =
  patchTasksReorderWithFormDataResponseSuccess

export const getPatchTasksReorderWithFormDataUrl = () => {
  return `http://localhost:3333/tasks/reorder`
}

export const patchTasksReorderWithFormData = async (
  patchTasksReorderWithFormDataBodyThree: PatchTasksReorderWithFormDataBodyThree,
  options?: RequestInit,
): Promise<patchTasksReorderWithFormDataResponse> => {
  const formData = new FormData()
  patchTasksReorderWithFormDataBodyThree.tasks.forEach((value) =>
    formData.append(`tasks`, JSON.stringify(value)),
  )

  const res = await fetch(getPatchTasksReorderWithFormDataUrl(), {
    credentials: 'include',
    ...options,
    method: 'PATCH',
    body: formData,
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: patchTasksReorderWithFormDataResponse['data'] = body
    ? JSON.parse(body)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchTasksReorderWithFormDataResponse
}

export const getPatchTasksReorderWithFormDataMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchTasksReorderWithFormData>>,
    TError,
    { data: PatchTasksReorderWithFormDataBodyThree },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchTasksReorderWithFormData>>,
  TError,
  { data: PatchTasksReorderWithFormDataBodyThree },
  TContext
> => {
  const mutationKey = ['patchTasksReorderWithFormData']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchTasksReorderWithFormData>>,
    { data: PatchTasksReorderWithFormDataBodyThree }
  > = (props) => {
    const { data } = props ?? {}

    return patchTasksReorderWithFormData(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PatchTasksReorderWithFormDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchTasksReorderWithFormData>>
>
export type PatchTasksReorderWithFormDataMutationBody =
  PatchTasksReorderWithFormDataBodyThree
export type PatchTasksReorderWithFormDataMutationError = unknown

export const usePatchTasksReorderWithFormData = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchTasksReorderWithFormData>>,
      TError,
      { data: PatchTasksReorderWithFormDataBodyThree },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchTasksReorderWithFormData>>,
  TError,
  { data: PatchTasksReorderWithFormDataBodyThree },
  TContext
> => {
  return useMutation(
    getPatchTasksReorderWithFormDataMutationOptions(options),
    queryClient,
  )
}
