/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetAttachmentsByTaskId200AttachmentsItem } from './getAttachmentsByTaskId200AttachmentsItem'

export type GetAttachmentsByTaskId200 = {
  attachments: GetAttachmentsByTaskId200AttachmentsItem[]
}
