/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetAttachmentsByTasks200AttachmentsItem } from './getAttachmentsByTasks200AttachmentsItem'

export type GetAttachmentsByTasks200 = {
  attachments: GetAttachmentsByTasks200AttachmentsItem[]
}
