/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type GetAttachmentsByTaskId200AttachmentsItemStatus =
  (typeof GetAttachmentsByTaskId200AttachmentsItemStatus)[keyof typeof GetAttachmentsByTaskId200AttachmentsItemStatus]

export const GetAttachmentsByTaskId200AttachmentsItemStatus = {
  pending: 'pending',
  scanning: 'scanning',
  clean: 'clean',
  infected: 'infected',
  error: 'error',
} as const
