/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetColumnsWithTasks200ItemCardsItemAssignee } from './getColumnsWithTasks200ItemCardsItemAssignee'
import type { GetColumnsWithTasks200ItemCardsItemLabel } from './getColumnsWithTasks200ItemCardsItemLabel'

export type GetColumnsWithTasks200ItemCardsItem = {
  id: string
  title: string
  order: number
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  assigneeId: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  dueDate?: string | null
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  updatedAt?: string | null
  /** @nullable */
  label?: GetColumnsWithTasks200ItemCardsItemLabel
  /** @nullable */
  assignee?: GetColumnsWithTasks200ItemCardsItemAssignee
  attachmentCount: number
}
