/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetColumnsKanban200ItemCardsItem } from './getColumnsKanban200ItemCardsItem'

export type GetColumnsKanban200Item = {
  id: string
  title: string
  cards: GetColumnsKanban200ItemCardsItem[]
}
