/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetColumnsWithTasks200ItemCardsItem } from './getColumnsWithTasks200ItemCardsItem'

export type GetColumnsWithTasks200Item = {
  id: string
  title: string
  cards: GetColumnsWithTasks200ItemCardsItem[]
}
