/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetColumns200ColumnsItem } from './getColumns200ColumnsItem'

export type GetColumns200 = {
  columns: GetColumns200ColumnsItem[]
}
