/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetColumnsKanban200ItemCardsItemAssignee } from './getColumnsKanban200ItemCardsItemAssignee'
import type { GetColumnsKanban200ItemCardsItemLabel } from './getColumnsKanban200ItemCardsItemLabel'

export type GetColumnsKanban200ItemCardsItem = {
  id: string
  title: string
  order: string
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  assigneeId: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  dueDate?: string | null
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  updatedAt?: string | null
  /** @nullable */
  label?: GetColumnsKanban200ItemCardsItemLabel
  /** @nullable */
  assignee?: GetColumnsKanban200ItemCardsItemAssignee
}
