/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type GetLabelsByProjectId200LabelsItem = {
  id: string
  name: string
  color: string
  projectId: string
}
