/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetLabelsByProjectId200LabelsItem } from './getLabelsByProjectId200LabelsItem'

export type GetLabelsByProjectId200 = {
  labels: GetLabelsByProjectId200LabelsItem[]
}
