/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetTasks200TasksItemAssignee } from './getTasks200TasksItemAssignee'
import type { GetTasks200TasksItemLabel } from './getTasks200TasksItemLabel'

export type GetTasks200TasksItem = {
  id: string
  title: string
  order: string
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  assigneeId: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  dueDate?: string | null
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  updatedAt?: string | null
  /** @nullable */
  label?: GetTasks200TasksItemLabel
  /** @nullable */
  assignee?: GetTasks200TasksItemAssignee
}
