/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type GetTasks200TasksItem = {
  id: string
  title: string
  order: number
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  description?: string | null
  dueDate?: unknown | null
  createdAt?: unknown | null
  updatedAt?: unknown | null
}
