/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetTasks200TasksItem } from './getTasks200TasksItem'

export type GetTasks200 = {
  tasks: GetTasks200TasksItem[]
}
