/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PatchColumnsReorderWithFormDataBodyThreeColumnsItem } from './patchColumnsReorderWithFormDataBodyThreeColumnsItem'

export type PatchColumnsReorderWithFormDataBodyThree = {
  columns: PatchColumnsReorderWithFormDataBodyThreeColumnsItem[]
}
