/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostAttachmentsUploadByTaskIdWithFormData201Status } from './postAttachmentsUploadByTaskIdWithFormData201Status'

export type PostAttachmentsUploadByTaskIdWithFormData201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  taskId: string
  fileName: string
  fileSize: number
  fileType: string
  storageKey: string
  status: PostAttachmentsUploadByTaskIdWithFormData201Status
  /** @nullable */
  createdAt?: string | null
}
