/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostTasksWithUrlEncoded201Assignee } from './postTasksWithUrlEncoded201Assignee'
import type { PostTasksWithUrlEncoded201Label } from './postTasksWithUrlEncoded201Label'

export type PostTasksWithUrlEncoded201 = {
  id: string
  title: string
  order: string
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  assigneeId: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  dueDate?: string | null
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  updatedAt?: string | null
  /** @nullable */
  label?: PostTasksWithUrlEncoded201Label
  /** @nullable */
  assignee?: PostTasksWithUrlEncoded201Assignee
}
