/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostTasksWithJson201Assignee } from './postTasksWithJson201Assignee'
import type { PostTasksWithJson201Label } from './postTasksWithJson201Label'

export type PostTasksWithJson201 = {
  id: string
  title: string
  order: string
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  assigneeId: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  dueDate?: string | null
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  updatedAt?: string | null
  /** @nullable */
  label?: PostTasksWithJson201Label
  /** @nullable */
  assignee?: PostTasksWithJson201Assignee
}
