/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PostAttachmentsUploadByTaskIdWithFormData201Status =
  (typeof PostAttachmentsUploadByTaskIdWithFormData201Status)[keyof typeof PostAttachmentsUploadByTaskIdWithFormData201Status]

export const PostAttachmentsUploadByTaskIdWithFormData201Status = {
  pending: 'pending',
  scanning: 'scanning',
  clean: 'clean',
  infected: 'infected',
  error: 'error',
} as const
