/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PostAttachmentsUploadByTaskIdWithUrlEncoded201Status =
  (typeof PostAttachmentsUploadByTaskIdWithUrlEncoded201Status)[keyof typeof PostAttachmentsUploadByTaskIdWithUrlEncoded201Status]

export const PostAttachmentsUploadByTaskIdWithUrlEncoded201Status = {
  pending: 'pending',
  scanning: 'scanning',
  clean: 'clean',
  infected: 'infected',
  error: 'error',
} as const
