/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostTasksWithFormData201Assignee } from './postTasksWithFormData201Assignee'
import type { PostTasksWithFormData201Label } from './postTasksWithFormData201Label'

export type PostTasksWithFormData201 = {
  id: string
  title: string
  order: string
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  assigneeId: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  dueDate?: string | null
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  updatedAt?: string | null
  /** @nullable */
  label?: PostTasksWithFormData201Label
  /** @nullable */
  assignee?: PostTasksWithFormData201Assignee
}
