/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type PostTasksWithFormData201Label = {
  name: string
  color: string
} | null
