/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostTasksWithFormData201Assignee } from './postTasksWithFormData201Assignee'

export type PostTasksWithFormData201 = {
  id: string
  title: string
  order: number
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  description?: string | null
  dueDate?: unknown | null
  createdAt?: unknown | null
  updatedAt?: unknown | null
  /** @nullable */
  assigneeId?: string | null
  /** @nullable */
  assignee?: PostTasksWithFormData201Assignee
}
