/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PostTasksWithJson201 = {
  id: string
  title: string
  order: number
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  dueDate?: string | null
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  updatedAt?: string | null
}
