/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PostColumnsWithFormData201 = {
  id: string
  title: string
  order: string
  projectId: string
}
