/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PutColumnsByIdWithUrlEncodedBodyTwo = {
  title?: string
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order?: number
}
