/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutTasksByIdWithUrlEncoded200Assignee } from './putTasksByIdWithUrlEncoded200Assignee'
import type { PutTasksByIdWithUrlEncoded200Label } from './putTasksByIdWithUrlEncoded200Label'

export type PutTasksByIdWithUrlEncoded200 = {
  id: string
  title: string
  order: string
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  assigneeId: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  dueDate?: string | null
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  updatedAt?: string | null
  /** @nullable */
  label?: PutTasksByIdWithUrlEncoded200Label
  /** @nullable */
  assignee?: PutTasksByIdWithUrlEncoded200Assignee
}
