/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutTasksByIdWithJson200Assignee } from './putTasksByIdWithJson200Assignee'
import type { PutTasksByIdWithJson200Label } from './putTasksByIdWithJson200Label'

export type PutTasksByIdWithJson200 = {
  id: string
  title: string
  order: string
  columnId: string
  /** @nullable */
  labelId: string | null
  /** @nullable */
  assigneeId: string | null
  /** @nullable */
  description?: string | null
  /** @nullable */
  dueDate?: string | null
  /** @nullable */
  createdAt?: string | null
  /** @nullable */
  updatedAt?: string | null
  /** @nullable */
  label?: PutTasksByIdWithJson200Label
  /** @nullable */
  assignee?: PutTasksByIdWithJson200Assignee
}
